### ISSUE TITLE
MULTNUM and MULTREG[T|P] definition

### ISSUE THREAD

**Issue by pgdr** [OPM/opm-parser#1014]
A minor discussion led to certain questions, and I want to see if I understand `MULTNUM` correctly.

If I want to work with _transmissibility_ or _pore volume_ multipliers (`MULTREGT` and `MULTREGP` resp.), is it the case that 

1. If I do not specify `MULTNUM` for a certain cell, it will be given `MULTNUM=1`?
2. Is `MULTNUM=0` in use?  Is it allowed?
3. Is there a relation between `MULTNUM` and inactive cells?  E.g., does `MULTNUM=1` imply that a cell is inactive, or vice versa?

And finally, if I want to set transmissibility multiplier `0.2718` (in the `XY` directions) between region `7` and `13`, do I add the following?
```
MULTREGT
7 13 0.2718 'XY' /
/
```

@totto82 @joakim-hove @jokva _I hope we can figure out this discussion here so we get documented behaviour._

**Comment by OPMUSER** [comment]
The correct form of the keyword is

-- 
-- SET TRANSMISSIBILITES ACROSS DIFFERENT RESERVOIRS TO ZERO TO ISOLATE 
RESERVOIRS
-- 
--    REGION    REGION      TRANS    DIREC NNC
--    FROM      TO          MULT     OPT OPTS
MULTREGT
       1*        1*          0.0      1*      'ALL'   / ALL REGIONS SEALED
/

To answer your questions:

1
	If I do not specify |MULTNUM| for a certain cell, it will be given 
|MULTNUM=1|? 	If it not specified then there should be no change so a 
MULTNUM = 1 is correct.
2
	Is MULTNUM=0 in use? Is it allowed?
	Yes it is allowed and is commonly used to prevent communication between 
two regions (separate fault blocks for example).
3
	Is there a relation between MULTNUM and inactive cells? E.g., does 
MULTNUM=1 imply that a cell is inactive, or vice versa?
	No, and inactive cell has zero pore volume so anything times zero is zero.
4
	And finally, if I want to set transmissibility multiplier 0.2718 (in 
the XY directions) between region 7 and 13, do I add the following?

MULTREGT
7 13 0.2718 'XY' /
/

	That depends. This is directionally dependent so your keyword only 
effects flow from 7 to 13, so you need to add the 13 to 7 line as well 
if you wish to down grade the transmissibility independent of the flow 
direction.



ThunderBird Signature File

Regards, David Baxendale Email: David.Baxendale@gmail.com

------------------------------------------------------------------------

**Comment by joakim-hove** [comment]
> 1. If I do not specify MULTNUM for a certain cell, it will be given MULTNUM=1?

Yes - that is the Eclipse default; and I saw to my relief that we have implemented that correctly.

> 2. Is MULTNUM=0 in use? Is it allowed?

As I see it these values are integer id's - so there should be nothing special with the numerical value 0; I have not seen it in use thoug,

> 3. Is there a relation between MULTNUM and inactive cells? 

I can not see how that should be the case, so I will answer: "No - the Eclipse data model does not per se enforce any relation between active/inactive cells and MULTNUM values".

I guess this thread was indirectly started by @totto82 in private communication; I must admit I did not understand that e-mail from @totto82 and would like to ask for a clarification.

**Comment by joakim-hove** [comment]
@totto82 and myself have had private communication, the current *belief* is that model2 problems are not related to `MULTREGT`
