### ISSUE TITLE
compatibility of windows and linux directory separators

### ISSUE THREAD

**Issue by hnil** [OPM/opm-parser#1033]
Given an input deck with include statement
INCLUDE
'..\MYDIR\MYFILE.INC'

which should work on windows to not work on linux where the normal way of writing would be

INCLUDE
'../MYDIR/MYFILE.INC'

Handling this case would make transfer of files between windows and linux simpler...

**Comment by joakim-hove** [comment]
> Handling this case would make transfer of files between windows and linux simpler...

Hmmm - I must admit I do not fully understand your question. My understanding of the situation regarding path separators is as follows:

1. opm-parser is using `boost::filesystem` for path operations; I assume that works transparently on Windows and Linux.

2. I *thought* Windows actually handled both `/` and `\` as path separator? 
 
> Handling this case would make transfer of files between windows and linux simpler...

Do you really mean *transfer of files* - or do you rather mean running the same deck on both windows and linux?

**Comment by atgeirr** [comment]
> Do you really mean transfer of files - or do you rather mean running the same deck on both windows and linux?

The second, running a deck with backslashes in it on Linux.

**Comment by joakim-hove** [comment]
NO - on Linux the path separator is `/` - on the other I think maybe Windows also will handle `/`. If windows can not handle `/` as path separator your best bet would be to use s script to convert between the two.

Sorry - closing.

**Comment by atgeirr** [comment]
I think, that if Eclipse on Linux supports backslash separators, perhaps we should support it too? Do you know if it does?

**Comment by OPMUSER** [comment]
Yes, it does but it does not handle spaces in directory or file names on 
Linux.
ThunderBird Signature File

Regards, David Baxendale Email: David.Baxendale@gmail.com

------------------------------------------------------------------------

**Comment by atgeirr** [comment]
> Yes, it does

Would it be a big effort to add this to opm-parser, @joakim-hove?

> but it does not handle spaces in directory or file names on
> Linux.

That is a strange difference, but not one we need to copy I think...

**Comment by joakim-hove** [comment]
> I think, that if Eclipse on Linux supports backslash separators, perhaps we should support it too? 

I guess I spoke my mind quite clearly by closing the case - but of course if the community as a whole argues that we should indeed support `\` as path separator on Linux we will of course look into it. I have no experience with this - but I feel quite uncomfortable implementing a file system semantics which is actually in conflict with the underlying platform.

My guess is that `/` actually works on Windows, and if that is the case I really think we should stick to `/`. So - before we do anything here I would like a clear statement of the status of Eclipse and `/` on Windows.

**Comment by joakim-hove** [comment]
> Would it be a big effort to add this to opm-parser, @joakim-hove?

I don't know - we might have to wrap/reimplement quite a lot of `boost::filesystem`

**Comment by blattms** [comment]
Maybe it is easier to provide a small script to users converting the
file path seperators.

**Comment by atgeirr** [comment]
> we might have to wrap/reimplement quite a lot of boost::filesystem

That sounds like something we won't do... Could we not just replace backslashes with slashes in strings from INCLUDE? Or would `"onedir\twodir"` get converted to a tab in the string (too early for us to do something about it)? Or are there other valid uses of backslashes that would be blocked?

**Comment by joakim-hove** [comment]
> Or would "onedir\twodir" get converted to a tab in the string (too early for us to do something about it)? Or are there other valid uses of backslashes that would be blocked?

I don't know - I just fear that this is opening up a can ow worms for limited gains. Before we proceed any further this must be clarified:

**My guess is that / actually works on Windows, and if that is the case I really think we should stick to /. So - before we do anything here I would like a clear statement of the status of Eclipse and / on Windows.**

**Comment by atgeirr** [comment]
> before we do anything here I would like a clear statement of the status of Eclipse and / on Windows

While this would be good to know, I think that we must handle it somehow. A slightly improved error message for the "include file not found" error would go a long way (perhaps scanning the string for backslashes, and if found, suggest replacing with slashes in the error message).

**Comment by andlaus** [comment]
> Could we not just replace backslashes with slashes in strings from INCLUDE? [...] Or are there other valid uses of backslashes that would be blocked?

that breaks the following funny corner case:

```
and@heuristix:~ > cd foo\\bar
and@heuristix:~/foo\bar >
```

i.e. on linux a backslash can even be part of file names. I have no idea if slashes can be part of windows file names, though...

**Comment by atgeirr** [comment]
> on linux a backslash can even be part of file names

I'm pretty sure explicitly disallowing that in Flow would be a service to the community rather than a hindrance...

**Comment by joakim-hove** [comment]
> I'm pretty sure explicitly disallowing that in Flow would be a service to the community rather than a hindrance...

That I agree - however it is still imposing a different file system semantics than the underlying platform; veeeeery skeptical.

**Comment by andlaus** [comment]
I agree, too. I'm not the one who's to decide whom's decks shall break, though...

**Comment by pgdr** [comment]
I agree with @joakim-hove and @blattms — if deemed necessary, we'll provide a script (in opm-utilities or opm-parser) that converts backslashes in `INCLUDE` statements to proper slashes.

That will be a one-off and the speed of the parser will be unaffected by this.

**Comment by OPMUSER** [comment]
I don't think this is a big deal, as it is more of inconvenience than a 
hindrance, so the script option would work for engineers.   I have run 
models built on Windows boxes, ran then under both Windows and Linux 
without having to change the file names. So if there is an option to run 
a script before running FLOW that would work.
ThunderBird Signature File

Regards, David Baxendale Email: David.Baxendale@gmail.com

------------------------------------------------------------------------

**Comment by hnil** [comment]
For information the file tested was generated by Petrel
-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2014.3 (64-bit) Schlumberger
-- User name   : XXXXXX
-- Date        :XXXXXXXXX
-- Project     : XXXXXXX
-- Generated ]
probably under windows...

**Comment by atgeirr** [comment]
> the file tested was generated by Petrel

Ouch!
