### ISSUE TITLE
Number of items in WCONINJE Eclipse keyword

### ISSUE THREAD

**Issue by gidiko** [OPM/opm-parser#1034]
I am looking into the manual of Eclipse 2014.2 and I see that WCONINJE has 15 items.

Comparing, in https://github.com/OPM/opm-parser/blob/master/opm/parser/share/keywords/000_Eclipse100/W/WCONINJE I count placeholders for 14 items.

I am super-new to working with Eclipse format, so perhaps I am missing something here, but perhaps this could be a quick edit. 

Thanks for this excellent effort!!

**Comment by OPMUSER** [comment]
Item 15 is for Thermal
ThunderBird Signature File

Regards, David Baxendale Email: David.Baxendale@gmail.com

------------------------------------------------------------------------

**Comment by gidiko** [comment]
For the label names in the json in the repo, something that would sound like "SURFACE_WATER_FRACTION" should be there it seems... I mean the "mapping" of what is described as "Surface volume proportion of water in a multiphase injector" in the reference manual...

**Comment by joakim-hove** [comment]
>For the label names in the json in the repo, something that would sound like "SURFACE_WATER_FRACTION" should be there it seems... 

You are absolutely right - such an item is missing between the existing items `SURFACE_OIL_FRACTION` and `SURFACE_GAS_FRACTION`. Feel free to submit a PR!

> Item 15 is for Thermal

Yes - we still have it though (appearing incorrectly as item 14). When it comes keywords which are slightly different in the different ECLIPSE versions we have not been very consequent. You will find both keywords limited to include only the `ECLIPSE100` items, and keywords with all items also from the other eclipse versions.

We have a system where a keyword can appear multiple times in the the subfolders here: https://github.com/OPM/opm-parser/tree/master/opm/parser/share/keywords - but it is not really used.

**Comment by GitPaean** [comment]
close with https://github.com/OPM/opm-common/pull/349
