### ISSUE TITLE
SWATINIT and ENDSCALE

### ISSUE THREAD

**Issue by totto82** [OPM/opm-parser#1049]
If SWATINIT is used, but ENDSCALE is not present in the deck, the EndpointScaling object should be initialized with default values.

**Comment by joakim-hove** [comment]
> If SWATINIT is used, but ENDSCALE is not present in the deck, the EndpointScaling object should be initialized with default values.

A bit uncertain on this; I do not know the callsite. But my guess is that if the `ENDSCALE` keyword is not present, it is in a way not possible to give sensible default values for the `EndpointScaling` object - it just does not apply?! As I said I am not familiar with the call-site, but I would assume that testing the `EndpointScaling` object for truthness before use could be the solution:

```C++
const auto& endPointScaling = runspec.endpointScaling( );
if (endPointsScaling) {
   // codepath for endpoint scaling active
} else {
   // endpoint scaling is not active.
}
```

Does this make sense?

**Comment by totto82** [comment]
The callsite is initFromDeck in EclEpsConfig.hpp in opm-material. Your solution is already applied to this location. But the problem with this solution is that endpoint scaling can in fact be active even thought ENDSCALE is not in use. This happens if SWATINIT is used.  All values in the ENDSCALE keywords have default values, so I don't see why it is not possible to give sensible default values to the EndpointScaling object even thought ENDSCALE is not present.

**Comment by joakim-hove** [comment]
> But the problem with this solution is that endpoint scaling can in fact be active even thought ENDSCALE is not in use. This happens if SWATINIT is used.

That sounds a bit weird to me - but anyways. The way I interpret is that: "If the deck contains `SWATINIT` the `EndpointScaling`object should evalute to `True` even if the deck does not contain the `ENDSCALE` keyword - i.e. somthing like this:

```txt

ENDSCALE    |  SWATINIT   |  EndpointScaling::operator bool()
-------------------------------------------------------------
YES         |   YES       | true
YES         |   NO        | true
NO          |   YES       | true
NO          |   NO        | false
-------------------------------------------------------------
```


> so I don't see why it is not possible to give sensible default values to the EndpointScaling object even thought ENDSCALE is not present.

Well - as I said I do not fully understand the situation; I will look in the manual - might be simple. But the current `EndpointScaling` object is not a direct replica of the `ENDSCALE`keyword.

**Comment by joakim-hove** [comment]
> But the problem with this solution is that endpoint scaling can in fact be active even thought ENDSCALE is not in use. This happens if SWATINIT is used.

I might very well misunderstand here - but I see indication in the manual that endpoint scaling should be used in the situation where the deck contains `SWATINIT` and not `ENDSCALE`- but I might misunderstand the situation?

**Comment by totto82** [comment]
> I might very well misunderstand here - but I see indication in the manual that endpoint scaling should be used in the situation where the deck contains SWATINIT and not ENDSCALE- but I might misunderstand the situation?

This is exactly the issue. The deck contains SWATINIT but not ENDSCALE. This means that the parser will not create the EndpointScaling object, but opm-material needs the EndpointScaling object to correctly support SWATINIT.

**Comment by joakim-hove** [comment]
@totto82 : can you call me.

**Comment by joakim-hove** [comment]
> This means that the parser will not create the EndpointScaling object

It will - but it evaluates to `false` and can not be used to anything; because *endpoint scaling is not active*. I just don't understand how you can query parameters for a non-existing object; it is a bit like asking what is the color of the car I do not have?

**Comment by joakim-hove** [comment]
OK - I was a bit slow here; understood now.

**Comment by andlaus** [comment]
> it is a bit like asking what is the color of the car I do not have?

welcome to the world of ECL ;)

**Comment by joakim-hove** [comment]
See: https://github.com/OPM/opm-parser/pull/1051

**Comment by GitPaean** [comment]
I believe default behavior is something will always cause problems from time to time. ECL has so many default things. It is much less obvious than doing something accordingly when we have some keywords.
