### ISSUE TITLE
Multisegment well option and ICDs keywords in Flow

### ISSUE THREAD

**Issue by igorbagno** [OPM/opm-parser#1050]
Hello, 

a question regarding the multisegment option in Flow. I've recently tried to implement it and it seems that the WELSEGS and WSEGDIMS keywords are accepted by the parser. When I try to introduce the COMPSEGS keyword (defining the completions in a multisegment well) the flow stops when launching. 

Is the multisegment option is supported by Flow in general?
And if yes, are the keywords describing the inflow control devices (ICDs) supported:
WSEGAICD, WSEGSICD, WSEGLABY and WSEFLIM?

I'll copy that issue to the opm-simulators folder as well.
Thanks and Regards,

Igor Bagno

**Comment by GitPaean** [comment]
I think none of the four keywords is supported by Flow at the moment.  We do have limited support for keywords WELSEGS and COMPSEGS. 

Please refer to  the original PR #633 for a little more information.  And we have one example in OPM-data  the folder wells_test_suite/MSW/2D_H__ .

**Comment by atgeirr** [comment]
@igorbagno I answered your questions in the opm-simulator issue.

**Comment by igorbagno** [comment]
Kai, thanks for your reply and the details. I'll have a look on the example you mentioned. Igor

**Comment by igorbagno** [comment]
Atgeirr, thanks, I'll reply to your comment in opm-simulator. Igor

**Comment by igorbagno** [comment]
Kai, the wells_test_suite contains WECON folder with test data only. Can you advise on where to find the MSW data, please?

**Comment by GitPaean** [comment]
Sorry, the just changed the directory for testing reason.  

The current path is msw_2d_h/2D_H__.DATA under OPM-data.

**Comment by igorbagno** [comment]
Kai, thanks, downloaded well. I'll have a look.

**Comment by igorbagno** [comment]
I'm closing that issue and leaving the one in opm-sumulator folder open.
