### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-parser#1070]
on my kuuntu 17.04 machine the opm-parser build now fails, probably due to merging #1065:

```
cmake "/home/and/src/opm-parser" "-DCMAKE_INSTALL_PREFIX=/usr/local" -DSIBLING_SEARCH=OFF -DCMAKE_BUILD_TYPE=Debug -DUSE_MPI=ON -DBUILD_TESTING=OFF -DCMAKE_C_COMPILER="/usr/bin/gcc" -DCMAKE_CXX_COMPILER="/usr/bin/g++" -DCMAKE_BUILD_TYPE=Custom -DCMAKE_CXX_FLAGS=" -Wall -Wunused -Wno-overloaded-virtual -Wno-cast-align -Wno-unknown-pragmas -fno-strict-aliasing -fstrict-overflow -g -march=native -DDEBUG=1"  "-DERT_ROOT=/home/and/src/libecl-install" "-DSUPERLU_ROOT=/home/and/src/external/SuperLU_4.3" "-DOPM_COMMON_ROOT=/home/and/src/opm-common"
-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- opm-parser version set to 2017.10 in dune.module
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   date_time
--   system
--   unit_test_framework
--   regex
-- Checking whether the file system is case-sensitive
-- File system is case-sensitive
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ERT_ROOT
    OPM_COMMON_ROOT
    SIBLING_SEARCH
    SUPERLU_ROOT
    USE_MPI


-- Build files have been written to: /home/and/src/opm-parser
--- calling make for opm-parser ---
----- using default flags $MAKE_FLAGS from /home/and/src/debug-gcc.opts -----
build directory: 
make
[  0%] Building C object external/cjson/CMakeFiles/cjson.dir/cJSON.c.o
[  0%] Built target cjson
[  1%] Building CXX object lib/json/CMakeFiles/opmjson.dir/JsonObject.cpp.o
[  2%] Linking CXX static library libopmjson.a
[  2%] Built target opmjson
[  3%] Building CXX object lib/json/CMakeFiles/runJsonTests.dir/tests/jsonTests.cpp.o
make[2]: *** No rule to make target 'boost_test-NOTFOUND', needed by 'lib/json/runJsonTests'.  Stop.
CMakeFiles/Makefile2:142: recipe for target 'lib/json/CMakeFiles/runJsonTests.dir/all' failed
make[1]: *** [lib/json/CMakeFiles/runJsonTests.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by andlaus** [comment]
BTW: the libboost-all-dev is installed so boost-test should be detected (and it was yesterday).

full log:

[CMakeOutput.txt](https://github.com/OPM/opm-parser/files/1046966/CMakeOutput.txt)

**Comment by joakim-hove** [comment]
> my kuuntu 17.04 machine the opm-parser build now fails

Is this dune-control?

**Comment by andlaus** [comment]
jup. but you can replicate this by just doing an in-source build.

**Comment by jokva** [comment]
What's the value of `Boost_UNIT_TEST_FRAMEWORK_DEBUG`?

**Comment by joakim-hove** [comment]
At my place an in-source (sic!) build does not pick the correct version of Boost - using the one found in `/usr` instead of the one provided by `-DCMAKE_PREFIX_PATH=` and then things fall apart - not clear if that is the same issue?

**Comment by jokva** [comment]
I doubt it. If you want boost to pick up some specific path you need to set variables that the `FindBoost` module wants - opm-parser doesn't interfere with that. 

https://cmake.org/cmake/help/v3.0/module/FindBoost.html

Pass `-DBOOST_ROOT` to suggest a different path than /usr/*

**Comment by andlaus** [comment]
> What's the value of Boost_UNIT_TEST_FRAMEWORK_DEBUG?

```
and@singularius:~/src/opm-parser|master > grep Boost_UNIT_TEST CMakeCache.txt 
Boost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG:FILEPATH=/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.a
Boost_UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE:FILEPATH=/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.a
//ADVANCED property for variable: Boost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG
Boost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE
Boost_UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE-ADVANCED:INTERNAL=1
```

**Comment by jokva** [comment]
Can you try something? Try and set IMPORTED_LOCATION_Debug along with IMPORTED_LOCATION_DEBUG at line 125.

**Comment by atgeirr** [comment]
I also get build failure after updating opm-parser, that could be the same as @andlaus' issue (or not). My output is:
```
atgeirr@galadriel:~/opm-build-debug/opm-parser-build$ cmake -C ~/debugopts.cmake ../opm-parser
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- opm-parser version set to 2017.10 in dune.module
-- The C compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   date_time
--   system
--   unit_test_framework
--   regex
-- Checking whether the file system is case-sensitive
-- File system is not case-sensitive
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/atgeirr/opm-build-debug/opm-parser-build
atgeirr@galadriel:~/opm-build-debug/opm-parser-build$ make
Scanning dependencies of target cjson
[  0%] Building C object external/cjson/CMakeFiles/cjson.dir/cJSON.c.o
[  0%] Built target cjson
Scanning dependencies of target opmjson
[  0%] Building CXX object lib/json/CMakeFiles/opmjson.dir/JsonObject.cpp.o
/Users/atgeirr/opm-build-debug/opm-parser/lib/json/JsonObject.cpp:26:10: fatal error: 'boost/filesystem/path.hpp' file not found
#include <boost/filesystem/path.hpp>
         ^
1 error generated.
make[2]: *** [lib/json/CMakeFiles/opmjson.dir/JsonObject.cpp.o] Error 1
make[1]: *** [lib/json/CMakeFiles/opmjson.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by joakim-hove** [comment]
Yes - I know; we have f...ed up quite badly when it comes to (at least) boost in non-standard locations. We have looked at it for several hours this afternoon with no success, must continue next week.

If someone understand the issue - and have a fix - feel free to cowboy merge. Reverting is also tricky since more than one repo was involved. Very sorry.

**Comment by dr-robertk** [comment]
I can second the above comments. Also fails on my machine.

**Comment by atgeirr** [comment]
I wish I knew before I merged... As long as Jenkins works it is not too bad, I can go back in time locally I guess.

**Comment by atgeirr** [comment]
If it helps: my boost is in a standard location (/usr/local), and is found during the generation phase (i.e. I do not set anyting custom w.r.t. boost).

**Comment by joakim-hove** [comment]
OK - you could try this: https://github.com/OPM/opm-parser/pull/1071 - it does *not* solve the full problem, but might solve it for people who have Boost in a standard location.

In my case the linker fails because it *insists* on using some too-old libraries from `/usr`; yes - I have tried various `-DDO_NOT_USE_SYSTEM_xxxx` switches - but to no avail.

**Comment by jokva** [comment]
Atgeirr's issue should be fixed with #1071

**Comment by jokva** [comment]
That being said, if you have boost in non-standard locations you will have to help cmake find it. Please refer to the `FindBoost` module documentation https://cmake.org/cmake/help/v3.0/module/FindBoost.html

**Comment by jokva** [comment]
Alright, I've figured out why this fails now and why I haven't seen it on a `/usr/include` system.

When the `IMPORTED` boost targets are created, only the `INTERFACE_SYSTEM_INCLUDE_DIRECTORIES` property is populated, because otherwise boost would warn a lot, and these are warnings we obviously don't care about. However, this property doesn't seem to correspond to `target_include_directores(SYSTEM ...)` as the documentation indicates, or maybe it only does for interface targets (from cmake 3+).

One fix is to do a `s/SYSTEM_//`, but then we get warnings from boost. The other is to figure out how to make cmake understand that boost headers should be `SYSTEM` includes without going the route of `include_directories`, which I'll look into now.

**Comment by jokva** [comment]
https://cmake.org/cmake/help/v3.0/prop_tgt/NO_SYSTEM_FROM_IMPORTED.html#prop_tgt:NO_SYSTEM_FROM_IMPORTED

So, according to this, `INTERFACE_INCLUDE_DIRECTORIES` from `IMPORTED` libraries are defaulted to `SYSTEM` on cmake >= 3.x, so not using `INTERFACE_SYSTEM_INTERFACE_DIRECTORIES` won't be that bad. However, I'd like to have this working properly on 2.8.12 as well.

**Comment by jokva** [comment]
Ok, so I've verified this works comfortably on cmake 3.x. I'll test some more on Tuesday on 2.8.12, and then merge a fix.

**Comment by andlaus** [comment]
> Yes - I know; we have f...ed up quite badly when it comes to (at least) boost in non-standard locations. We have looked at it for several hours this afternoon with no success, must continue next week.

actually, my issue is for the kubuntu packages, so their location should be as standard as it gets ;)

possibly, we should take this issue as an opportunity to think about getting rid of boost entirely in the medium term -- it has not been the first time that boost caused trouble and I strongly suspect that it will not be the last time. it may thus be less effort to rip it out than it is to keep fixing the headaches it comes with.

**Comment by jokva** [comment]
That assessment is 100% wrong, at least until you make C++17 a requirement.

**Comment by jokva** [comment]
Besides, this has nothing to do with boost - the same thing would've happened with any third-party library. What went wrong here is partly my misunderstand, poor cmake documentation (because you're really not meant to do this, you're meant to use `target_link_libraries` on interface libraries but that's a 3.x feature, and some minor pain migrating to a better makefile layout.

Boost is used both for *fast* number parsing, file system interaction *and* regular expression support, and until gcc6+ is available, nothing really replaces boost, and definitely not with less headache.

**Comment by andlaus** [comment]
> That assessment is 100% wrong

no it is not, because regardless of what you position about the boost dependency is, boost *did* frequently cause trouble in the past ;). I would go even so far to assert that it causes the majority of build system related  issues that I experience on my machine. (be aware that there are quite a few of these for which I don't open bug reports.)

> at least until you make C++17 a requirement.

what features to you think cannot be replaced by plain C++-2011 using a few extra lines of code? 

> Besides, this has nothing to do with boost

to me it looks a hell like a lot to do with this dependency.

> the same thing would've happened with any third-party library.

yes, but FindBoost tends to screw up regularly. Also, the C++ ABI incompatibilities of recent GCCs certainly don't help.

> Boost is used both for fast number parsing, file system interaction and regular expression support

if really necessary, the few lines of code for the number parsing can be copy-and-pasted and while at this probably considerably simplified (I did this with eWoms' AlignedAllocator class), the filesystem can easily be replaced by libecl stuff and regex support is already present in c++-2011 (GCC 4.9 or newer required, though). The unit testing framework stuff is also not terribly hard to replace as far as I can see.

**Comment by akva2** [comment]
Boost is THE major portability issue. I have spent stupid amounts of time on fixing all the headaches it causes on various platforms. Not commenting on whether it is needed but it is way above average when it comes to pain. It comes with it nature of being 'frontline' code.

**Comment by jokva** [comment]
> what features to you think cannot be replaced by plain C++-2011 using a few extra lines of code?

Filesystem, regex (needs newer libstdc++), (fast) number parsing.

> to me it looks a hell like a lot to do with this dependency.

It would've happened with *any* other dependency. It was cmake misconfiguration.

But I can't be bothered discussing this with you anymore, because we're not getting anywhere.

**Comment by andlaus** [comment]
> It would've happened with any other dependency.

that's why me (and @akva2 and probably most other people) would strongly prefer not having any dependency. (besides the c++ standard library.)

**Comment by andlaus** [comment]
> But I can't be bothered discussing this with you anymore, because we're not getting anywhere.

If you're happy with spending your workdays on fixing weird boost-related issues instead of doing something productive, that's fine with me, but obviously I'm not your boss.

**Comment by jokva** [comment]
Please reopen if https://github.com/OPM/opm-parser/pull/1073 doesn't solve the issue.

**Comment by atgeirr** [comment]
#1071 was not sufficient to resolve my problems, but with #1073 also it seems to work for me. However there are far fewer tests than before, is that intentional?

**Comment by jokva** [comment]
Yes, a few test files are merged together to reduce compile times.

**Comment by jokva** [comment]
@atgeirr Your snippet contains no information. What's the cmake version, what is the compile line of `make VERBOSE=1 opmjson`?

**Comment by atgeirr** [comment]
cmake version is 3.3.0

The compile line I can get later (but do you need the pre-patch one?)

**Comment by jokva** [comment]
No, post-patch (i.e. current master).

**Comment by atgeirr** [comment]
After doing `touch lib/json/JsonObject.cpp` to trigger rebuilding and then the make command you suggested, I get this:
```
Scanning dependencies of target opmjson
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f lib/json/CMakeFiles/opmjson.dir/build.make lib/json/CMakeFiles/opmjson.dir/build
[  0%] Building CXX object lib/json/CMakeFiles/opmjson.dir/JsonObject.cpp.o
cd /Users/atgeirr/opm-build-debug/opm-parser-build/lib/json && /usr/bin/clang++   -DBOOST_FILESYSTEM_VERSION=3 -std=c++11 -pipe -std=c++0x -pedantic -Wall -Wextra -Wformat-nonliteral -Wcast-align -Wpointer-arith -Wmissing-declarations -Wcast-qual -Wshadow -Wwrite-strings -Wchar-subscripts -Wredundant-decls -Wno-unused-local-typedef -Wno-keyword-macro -Wno-missing-braces -pedantic -Wall -Wextra -Wformat-nonliteral -Wcast-align -Wpointer-arith -Wmissing-declarations -Wcast-qual -Wshadow -Wwrite-strings -Wchar-subscripts -Wredundant-decls -O0 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I/Users/atgeirr/opm-build-debug/opm-parser/lib/json/include -I/Users/atgeirr/opm-build-debug/opm-parser/external/cjson -isystem /usr/local/include    -o CMakeFiles/opmjson.dir/JsonObject.cpp.o -c /Users/atgeirr/opm-build-debug/opm-parser/lib/json/JsonObject.cpp
[100%] Linking CXX static library libopmjson.a
cd /Users/atgeirr/opm-build-debug/opm-parser-build/lib/json && /usr/local/Cellar/cmake/3.3.0/bin/cmake -P CMakeFiles/opmjson.dir/cmake_clean_target.cmake
cd /Users/atgeirr/opm-build-debug/opm-parser-build/lib/json && /usr/local/Cellar/cmake/3.3.0/bin/cmake -E cmake_link_script CMakeFiles/opmjson.dir/link.txt --verbose=1
/usr/bin/ar cq libopmjson.a  CMakeFiles/opmjson.dir/JsonObject.cpp.o ../../external/cjson/CMakeFiles/cjson.dir/cJSON.c.o
/usr/bin/ranlib libopmjson.a
[100%] Built target opmjson
```

**Comment by dr-robertk** [comment]
@jokva So far, nothing has been fixed. You'll have to try harder. I get the same issues as before you started fixing things, that is  boost_test-NOTFOUND and boost_regex-NOTFOUND.

But one thing's for sure: opm-parser is now stand-alone, i.e. can't be used with anything else any more.

**Comment by joakim-hove** [comment]
> So far, nothing has been fixed. 

That is not entirely true; the build has been restored on the Statoil vintage system and also @atgeirr seems to confirm it works again on his machine.

> I get the same issues as before you started fixing things, that is boost_test-NOTFOUND and boost_regex-NOTFOUND.

OK :-(

**Comment by jokva** [comment]
> @jokva So far, nothing has been fixed. You'll have to try harder. I get the same issues as before you started fixing things, that is boost_test-NOTFOUND and boost_regex-NOTFOUND.

Then I need more information on your system. cmake version, output from `cmake ..` in a clean build dir and output from `make VERBOSE=1`

**Comment by dr-robertk** [comment]
@jokva Isn't it as simple as boost checks worked before, so restore to that implementation? It will take some time to create the output since I have reverted my opm tool chain to something that works because I actually don't have time for this right now.

**Comment by jokva** [comment]
No, it's not that simple.

**Comment by dr-robertk** [comment]
Because?

**Comment by jokva** [comment]
Because that would require reverting across three repositories, and leaves ewoms in a broken state.

**Comment by dr-robertk** [comment]
Well... that's probably the easier option.

**Comment by jokva** [comment]
It works on travis, it works on jenkins, it works for Atgeirr and it works on my machine, and it seems to be working for Markus too. The easier option is for you to investigate your system.

**Comment by andlaus** [comment]
for me it also does not work:

```
cmake "/home/and/src/opm-parser" "-DCMAKE_INSTALL_PREFIX=/usr/local" -DSIBLING_SEARCH=OFF -DCMAKE_BUILD_TYPE=Debug -DUSE_MPI=ON -DBUILD_TESTING=OFF -DCMAKE_C_COMPILER="/usr/bin/gcc" -DCMAKE_CXX_COMPILER="/usr/bin/g++" -DCMAKE_BUILD_TYPE=Custom -DCMAKE_CXX_FLAGS=" -Wall -Wunused -Wno-overloaded-virtual -Wno-cast-align -Wno-unknown-pragmas -fno-strict-aliasing -fstrict-overflow -g -march=native -DDEBUG=1"  "-DERT_ROOT=/home/and/src/libecl-install" "-DSUPERLU_ROOT=/home/and/src/external/SuperLU_4.3" "-DOPM_COMMON_ROOT=/home/and/src/opm-common"
-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- opm-parser version set to 2017.10 in dune.module
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   date_time
--   system
--   unit_test_framework
--   regex
-- Checking whether the file system is case-sensitive
-- File system is case-sensitive
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ERT_ROOT
    OPM_COMMON_ROOT
    SIBLING_SEARCH
    SUPERLU_ROOT
    USE_MPI


-- Build files have been written to: /home/and/src/opm-parser
--- calling make for opm-parser ---
----- using default flags $MAKE_FLAGS from /home/and/src/debug-gcc.opts -----
build directory: 
make -j3
Scanning dependencies of target cjson
[  0%] Building C object external/cjson/CMakeFiles/cjson.dir/cJSON.c.o
[  0%] Built target cjson
Scanning dependencies of target opmjson
[  1%] Building CXX object lib/json/CMakeFiles/opmjson.dir/JsonObject.cpp.o
[  2%] Linking CXX static library libopmjson.a
[  2%] Built target opmjson
Scanning dependencies of target runJsonTests
Scanning dependencies of target genkw
make[2]: *** No rule to make target 'boost_test-NOTFOUND', needed by 'lib/json/runJsonTests'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[  3%] Building CXX object lib/json/CMakeFiles/runJsonTests.dir/tests/jsonTests.cpp.o
[  5%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Deck/Deck.cpp.o
[  5%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Parser/createDefaultKeywordList.cpp.o
[  6%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Deck/DeckItem.cpp.o
[  7%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Deck/DeckKeyword.cpp.o
CMakeFiles/Makefile2:142: recipe for target 'lib/json/CMakeFiles/runJsonTests.dir/all' failed
make[1]: *** [lib/json/CMakeFiles/runJsonTests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Deck/DeckRecord.cpp.o
[  9%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Generator/KeywordGenerator.cpp.o
[ 10%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Generator/KeywordLoader.cpp.o
[ 11%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Parser/MessageContainer.cpp.o
[ 12%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Parser/ParseContext.cpp.o
[ 13%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Parser/ParserEnums.cpp.o
[ 14%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Parser/ParserItem.cpp.o
[ 15%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Parser/ParserKeyword.cpp.o
[ 15%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/Parser/ParserRecord.cpp.o
[ 16%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/RawDeck/RawKeyword.cpp.o
[ 17%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/RawDeck/RawRecord.cpp.o
[ 18%] Building CXX object lib/eclipse/CMakeFiles/genkw.dir/RawDeck/StarToken.cpp.o
^Clib/eclipse/CMakeFiles/genkw.dir/build.make:374: recipe for target 'lib/eclipse/CMakeFiles/genkw.dir/RawDeck/RawKeyword.cpp.o' failed
make[2]: *** [lib/eclipse/CMakeFiles/genkw.dir/RawDeck/RawKeyword.cpp.o] Interrupt
lib/eclipse/CMakeFiles/genkw.dir/build.make:398: recipe for target 'lib/eclipse/CMakeFiles/genkw.dir/RawDeck/RawRecord.cpp.o' failed
make[2]: *** [lib/eclipse/CMakeFiles/genkw.dir/RawDeck/RawRecord.cpp.o] Interrupt
lib/eclipse/CMakeFiles/genkw.dir/build.make:422: recipe for target 'lib/eclipse/CMakeFiles/genkw.dir/RawDeck/StarToken.cpp.o' failed
make[2]: *** [lib/eclipse/CMakeFiles/genkw.dir/RawDeck/StarToken.cpp.o] Interrupt
CMakeFiles/Makefile2:236: recipe for target 'lib/eclipse/CMakeFiles/genkw.dir/all' failed
make[1]: *** [lib/eclipse/CMakeFiles/genkw.dir/all] Interrupt
Makefile:127: recipe for target 'all' failed
make: *** [all] Interrupt
```

this is kubuntu 17.04 (boost-1.62). it works fine with the version from june 1.

[CMakeCache.txt](https://github.com/OPM/opm-parser/files/1054730/CMakeCache.txt)
[CMakeOutput.txt](https://github.com/OPM/opm-parser/files/1054731/CMakeOutput.txt)

**Comment by dr-robertk** [comment]
> But for as long as it works for you, you're free to stay on the old system a bit longer locally.

Which means it shouldn't have been merged in the first place since it's obviously not a very sound patch.

**Comment by jokva** [comment]
@andlaus Try this: https://github.com/OPM/opm-parser/pull/1075

**Comment by andlaus** [comment]
with #1075 it works on my machine.

**Comment by jokva** [comment]
Considering this fixed.
