### ISSUE TITLE
Default-constructed `Deck` has invalid `size()`

### ISSUE THREAD

**Issue by bska** [OPM/opm-parser#1122]
The default constructor for [`Deck`](https://github.com/OPM/opm-parser/blob/master/lib/eclipse/Deck/Deck.cpp#L123) generates a [`DeckView`](https://github.com/OPM/opm-parser/blob/master/lib/eclipse/Deck/Deck.cpp#L111-L117) from an empty `std::vector<DeckKeyword>`.

This, in turn, means that the `first` and `last` members of the underlying `DeckView` are essentially default-constructed too and that neither of them are reachable from the other.  Since function `std::distance()` requires that `last` be reachable from `first` (prior to C++11) and that, additionally for random-access iterators, `first` be reachable from `last` (post C++11), this violates one of the constraints on the function.  Therefore, any client code that calls `Deck::size()` on a default-constructed `Deck` has undefined behaviour.

Since the `Schedule` class contains default-constructed `Deck`s within its `m_modifierDeck` data member, that covers essentially every user of class `Schedule`.  This is easily seen when running the [`GeomodifierTests`](https://github.com/OPM/opm-parser/blob/master/lib/eclipse/tests/GeomodifierTests.cpp#L89) in a checked-iterator build which will produce diagnostic messages akin to
```
Running 1 test case...
/usr/include/c++/5/debug/safe_iterator.h:758:error: attempt to compute the 
    difference between a singular iterator to a singular iterator.

Objects involved in the operation:
iterator "lhs" @ 0x0x7ffd40ce72a0 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKN3Opm11DeckKeywordENSt9__cxx19986vectorIS4_SaIS4_EEEEENSt7__debug6vectorIS4_S9_EEEE (constant iterator);
  state = singular;
}
iterator "rhs" @ 0x0x7ffd40ce7270 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKN3Opm11DeckKeywordENSt9__cxx19986vectorIS4_SaIS4_EEEEENSt7__debug6vectorIS4_S9_EEEE (constant iterator);
  state = singular;
}
unknown location(0): fatal error: in "CheckUnsoppertedInSCHEDULE": signal: SIGABRT (application abort requested)
/home/bska/work/opm/src/opm/opm-parser/lib/eclipse/tests/GeomodifierTests.cpp(89): last checkpoint

*** 1 failure is detected in the test module "GeoModifiersTests"
```

**Comment by joakim-hove** [comment]
Thank you for the detailed analysis - we will have to look into this.

**Comment by bska** [comment]
> Thank you for the detailed analysis - we will have to look into this.

Actually, my initial analysis is at best incomplete and at worst incorrect.  The `Deck(vector<DeckKeyword>&&)` constructor passing `x.begin()` and `x.end()` as arguments to the two-parameter `DeckView` constructor and then subsequently moving the source object (`x`) into a private data member is at least part of it.  While move-construction of a `vector` generally does not invalidate iterators (although it does make them refer to elements that are in a different container), the operation (i.e., the move-construction) **does** invalidate the `end()` iterator of the container.

That's probably a show-stopper and I don't see any way of fixing it other than adding (private) set-operations for `first` and `last` or to switch private inheritance into containment and making the `DeckView` data member refer to the `Deck::keywordList` sub-object.

**Comment by atgeirr** [comment]
> switch private inheritance into containment

This is probably a good idea anyway. I have used private inheritance myself and regretted it later! I do not know what effort would be required here though to do it.

**Comment by JensGM** [comment]
Could you try this patch https://github.com/OPM/opm-parser/pull/1126 and see if that fixes your issue, or part of it?

**Comment by bska** [comment]
> Could you try this patch #1126 and see if that fixes your issue, or part of it?

I can no longer reproduce the issue I was seeing.  I'll close this issue.  Thanks a lot.
