### ISSUE TITLE
Returning pointer to a pointer for m_eqldims in TableManager

### ISSUE THREAD

**Issue by kel85uk** [OPM/opm-parser#1172]
In `lib/eclipse/EclipseState/Tables/TableManager.cpp`

Noticed that the function `getEqldims()` returns `*m_eqldims`. Should it be just `m_eqldims`? This is because it is already of type `shared_ptr<Eqldims>`?

**Comment by akva2** [comment]
it is a function returning a reference so pointer has to be deref'd. what is confusing here ? a shared_ptr pointer follows normal pointer semantics.

**Comment by kel85uk** [comment]
@akva2 Ah, true that. Thanks for the clarification.

**Comment by pgdr** [comment]
@kel85uk Thanks for the comment.  The underlying problem is that `m_eqldims` is a shared pointer, and should either have been a value or a unique pointer.  Thanks for pointing that out.
