### ISSUE TITLE
does m_messages of Schedule output some where during running?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-parser#1207]
I could not find it anywhere in the output files or the screen output.  Thanks.

**Comment by joakim-hove** [comment]
Those message are passed from the `MessageContainer` to the logging facilities by the simulator.

**Comment by GitPaean** [comment]
Okay. thanks.  `output_cout_` in `FlowMainEbos` is false, so I could not see any this message. But I did not find a way to make it `true` either. Anyway, it should be fixed from the simulator side.
