### ISSUE TITLE
Cmake BUILD_SHARED_LIBS obtion not working

### ISSUE THREAD

**Issue by sveinung-r** [OPM/opm-parser#1212]
Building with cmake BUILD_SHARED_LIBS option does not work after commit d89e1c024ffd279de09d0d40ae0a1d6c327944c9.

**Comment by akva2** [comment]
please confirm that https://github.com/OPM/opm-common/pull/334 does the job for you.

**Comment by akva2** [comment]
ehm, in combination with https://github.com/OPM/opm-parser/pull/1214

**Comment by sveinung-r** [comment]
I can confirm that this works.
