### ISSUE TITLE
Findopm-data never found when included

### ISSUE THREAD

**Issue by blattms** [OPM/opm-parser#1225]
I now get the following Cmake error
```
Make Error at CMakeLists.txt:61 (include):
  include could not find load file:

    Findopm-data
```
no matter whether opm-data is lying in the the same directory as opm-parser or not.
No idea why this was not noticed before or surfaced just now.

**Comment by blattms** [comment]
will try to fix myself.

**Comment by GitPaean** [comment]
Hi, all the things from opm-parser is in opm-common now. We do not use opm-parser anymore.

**Comment by akva2** [comment]
and opm-data is now opm-tests.
