### ISSUE TITLE
No rule to make target 'opmparser-NOTFOUND'

### ISSUE THREAD

**Issue by rksin8** [OPM/opm-parser#1227]
Hi, I am getting an error:

![d2](https://user-images.githubusercontent.com/22324848/43060858-0beac440-8e96-11e8-9481-7d9b41bc8540.png)

opm-parser module is already installed. I am using dune2.4, opm2017.04 and dumux2.12.
![d](https://user-images.githubusercontent.com/22324848/43060660-38afc224-8e95-11e8-894a-8e30c2260526.png)

Any idea how to fix this?
Thank you!

**Comment by andlaus** [comment]
seems like you're using quite old OPM and dune releases (the newest are 2018.04 and 2.6). anyway, the opm-parser module has been superseded by [`opm-common`](https://github.com/OPM/opm-common) so the people who can actually help you with your issue might not see this one, i.e., you might want to report it over there.

**Comment by alfbr** [comment]
There have been recent efforts to make building dumux with opm and dune easier. You will find the relevant discussions and contributions here:
https://github.com/OPM/opm-grid/pull/327
https://github.com/OPM/opm-common/pull/302
https://github.com/OPM/opm-common/pull/455

Hence, I recommend that you move over to compiling the latest OPM code from git. You can keep Dune at 2.4. Please note that the modules opm-parser, opm-output and opm-core are incorporated into other modules, so you should not compile them anymore. You find the current build order here:
https://opm-project.org/?page_id=231
Please also note that you can turn off building of all Eclipse file support stuff when building opm-common, just set the cmake variable for it.

**Comment by blattms** [comment]
@alfbr's approach might only work if you switch to the master of dumux (as @berndflemisch made some changes there to support this). Not sure if this is what you want.

If I recall corrently then dumux needs patched versions of opm-parser.  There is a file bin/installexternal.sh in dumux  that might do the job for you. But you should consult the [Dumux Handbook](http://www.dumux.org/documents/dumux-handbook-2.12.pdf) on page 11 on this. If that does not help ask on the [Dumux mailinglist](https://listserv.uni-stuttgart.de/mailman/listinfo/dumux) how it exactly works.

**Comment by berndflemisch** [comment]
This corresponds to [Dumux issue 531](https://git.iws.uni-stuttgart.de/dumux-repositories/dumux/issues/531).

**Comment by rksin8** [comment]
Problem solved with latest modules.  What I did mentioned here: [Dumux issu 531](https://git.iws.uni-stuttgart.de/dumux-repositories/dumux/issues/531#note_16419)

Thank you for help.

**Comment by berndflemisch** [comment]
Great that it worked out!

**Comment by blattms** [comment]
We would like to prevent other users from
experiencing the same problems and jumping through the same hoops

It seems that you still had to manually change some cmake files
(opm-common-config.cmake, opm-common-prereqs.cmake, and
opm-grid-prereqs.cmake). Please tell us what you had to change there.

In what module did you have to comment out install_hook?

What error did you experience with set(ENABLE_ECL_INPUT ON)?

**Comment by rksin8** [comment]
- The changes in cmake files, i don't remember exactly.  I changed based on error messages. 

-set(ENABLE_ECL_INPUT ON) gives this error:
![opm3](https://user-images.githubusercontent.com/22324848/43174451-61e466ea-8ffd-11e8-972e-5bd96d5c3606.png)
​while building opm-common master. the master modules build successfully without dune but with dune gives above error.

**Comment by bska** [comment]
> ```cmake
> set(ENABLE_ECL_INPUT ON)
> ```
> gives this error:
>```
> undefined reference to `util_fnmatch'
>```

Function [`util_fnmatch`](https://github.com/Statoil/libecl/blob/master/lib/util/util.c#L4631-L4643) is provided by [LibECL](https://github.com/Statoil/libecl).  If you have not already done so, you need to somehow acquire that library&mdash;perhaps by compiling it yourself&mdash;and then ensure that the library is found during system probing (i.e., when running `cmake`).

**Comment by blattms** [comment]
The compile error happens in opm-common. That needs to/should work without user interaction.
