### ISSUE TITLE
WCONHIST - RESV

### ISSUE THREAD

**Issue by osae** [OPM/opm-parser#202]
In Schedule.cpp (line 254) we find the following comment:

   /*
     This is an awkward situation. The current control mode variable
     points to a control which has not been specified in the deck; i.e. a
     situation like this:

       WCONHIST 
          'WELL'      'OPEN'      'RESV'      0.000      0.000      0.000  5* /
       /
     
     We have specified that the well should be controlled with 'RESV'
     mode, but actual RESV value has been defaulted. ECLIPSE seems to
     handle this, but the well machinery in OPM-Core keeps close track of
     which controls are available, i.e. have a value set, and will be
     confused by this. We therefor throw here; the fix is to modify the
     deck to set an explicit value for the defaulted control, or
     alternatively change control mode.
   */
   
Actually, there does not appear to be any entry available for an explicit value of RESV under WCONHIST.  The volume is to be computed during simulation from the given phase composition representing historical well rates.  Not very exciting (all zero) in the example chosen above, but the combination of WCONHIST and RESV is extensively used for the Norne case, see INCLUDE/BC0407_HIST01122006.SCH.  
This issue must of course be considered in connection with current or future functionality available from opm-core ...

**Comment by joakim-hove** [comment]
Closing - according to: #248
