### ISSUE TITLE
WCONINJE - GRUP

### ISSUE THREAD

**Issue by osae** [OPM/opm-parser#203]
Placing a well under group control  currently causes a throw:
(opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp, line 340)

WCONINJE 
'F-3H'     'WATER'      'STOP'     'GRUP '  13000.000  1*    450.000  1*   19  1* /
/

For Norne: a single occurrence, might well be neglected?
Consider what functionality actually supported by opm-core...

**Comment by joakim-hove** [comment]
Too old - please reopen if still relevant.
