### ISSUE TITLE
Optional TABDIMS keyword must be present

### ISSUE THREAD

**Issue by rolk** [OPM/opm-parser#218]
(HEAD(opm-parser) = 5a097b3, HEAD(opm-core) = 55427b2)

Consider the following example program, called `whereismytabdims.cpp`:

    #include <opm/parser/eclipse/Parser/Parser.hpp>
    #include <memory>
    #include <string>

    int main () {
        std::string s ("SWOF\n0 0 0 0\n/\n");
        //s = "TABDIMS\n/\n" + s;
        auto parser = std::make_shared <Opm::Parser> ();
        auto deck = parser->parseString (s);
        return 0;
    }

with the following build file, `CMakeLists.txt`:

    cmake_minimum_required (VERSION 2.8)
    project (wheresmytabdims)
    enable_language (CXX)
    find_package (opm-core REQUIRED)
    include_directories (${opm-core_INCLUDE_DIRS})
    link_directories (${opm-core_LIBRARY_DIRS})
    add_definitions (${opm-core_DEFINITIONS})
    add_executable (wheresmytabdims wheresmytabdims.cpp)
    target_link_libraries (wheresmytabdims ${opm-core_LIBRARIES})

(I include opm-core instead of opm-parser because the latter does not generate an opm-parser-config.cmake file; by include opm-core, I get all the settings).

Running this program results in the following error:

    terminate called after throwing an instance of 'std::invalid_argument'
      what():  Keyword: TABDIMS is not found in the container
    Aborted (core dumped)

If I uncomment the second statement, it works.

**Comment by joakim-hove** [comment]
Fixed in: https://github.com/OPM/opm-parser/pull/412
