### ISSUE TITLE
WCONPROD seems to confuse pressure and gas rate control

### ISSUE THREAD

**Issue by rolk** [OPM/opm-parser#223]
If I specify this keyword in the SCHEDULE section:

    WCONPROD
    	p1   OPEN   BHP   -1    -1   -1   -1   -1   97   /
    /

I get the exception/error message:

    Gas phase not active and GRAT control specified.

(thrown in https://github.com/OPM/opm-core/blob/master/opm/core/wells/WellsManager.cpp#L484). It is correct in that there is no gas phase in the simulation, but not that gas rate control is specified.

**Comment by joakim-hove** [comment]
Too old - please reopen if still relevant.
