### ISSUE TITLE
Faulty handling of WCONHIST/RESV

### ISSUE THREAD

**Issue by bska** [OPM/opm-parser#224]
The handling of keyword `WCONHIST`, and especially the `RESV` control mode is currently wrong and I don't think the situation can be corrected without non-local code changes either.

Consider the following example from `opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp` (ca. line 260).
```
WCONHIST
-- Name     Open?    Mode    ORAT    WRAT    GRAT
  'WELL'    'OPEN'   'RESV'  0.000   0.000   0.000  5* /
/
```
The surrounding comment states that this is undefined because the `RESV` control is defaulted (and the code throws an exception in this case).  Unfortunately, that reasoning is not true.  If this were `WCONPROD` then the `RESV` control target (item 8) would indeed be defaulted and terminating the process would be appropriate.

In the case of `WCONHIST`, however, the `RESV` control mode is a bit more subtle.  In this case the simulator must translate the surface rates (`ORAT`, `WRAT`, `GRAT`) to reservoir conditions (by means average conditions calculated at the beginning of the time step) and then **sum** the resulting (reservoir) rate values to compute the actual `RESV` target.  As the above values are all zero this would correspond to `RESV=0` irrespective of field conditions, but non-zero values of the surface rates will lead to a non-zero `RESV` target.

I'm afraid I don't have a suggested solution to this problem, but it may be that we cannot use a single function (`Schedule::handleWCONProducer()`) to handle all aspects of *both* `WCONPROD` and `WCONHIST`.

I also apologise for providing incorrect information during the initial design and implementation of the `WCONHIST` support.

**Comment by joakim-hove** [comment]
Closing - according to: #248
