### ISSUE TITLE
The parser does not support defaulting the connection factor of a well completion

### ISSUE THREAD

**Issue by bska** [OPM/opm-parser#252]
By explicit design, the `COMPDAT` handling code (`.../Schedule/Completion.cpp`) does not support defaulting the connection factor of a completion. Specifically, the following block  in lines 63--67 of the `.cpp` file (method `Completion::completionsFromCOMPDATRecord()`) prevents defaults
```C++
{
    DeckItemConstPtr CFItem = compdatRecord->getItem("CF");
    if (CFItem->defaultApplied())
        throw std::invalid_argument("The connection factor item can not be defaulted");
}
```
Is there a technical reason for this restriction?

Despite its many shortcomings there is a fall-back method to compute connection factors in module opm-core's `WellManager` class.  Would it be possible to lift the restriction, or possibly make it conditional on some criterion?

**Comment by joakim-hove** [comment]
Too old - please reopen if still relevant.
