### ISSUE TITLE
Default values for SWL-family in the case of a non-global 'box'

### ISSUE THREAD

**Issue by osae** [OPM/opm-parser#277]
From the Norne deck:
```
COPY
  'SGU'   'ISGU'    1 46 1 112  5  22 /   -- i.e not defined for layer 1-4,   need to pick default values from saturation tables ...
/
```
By changing default value to be outside 0-1, e.g.
```
SupportedDoubleKeywordInfo( "ISGU"   , -0.1, "1" )
```
it will be possible later  to identify defaulted values and replace them with table look-ups as needed.

Is this a reasonable fix???

**Comment by joakim-hove** [comment]
Too old - please reopen if still relevant.
