### ISSUE TITLE
MULTREGT requires MULTNUM keyword in the deck.

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-parser#311]
When run with the currently available NORNE deck I get the following exception:

Program threw an exception: MULTREGT record is based on region: MULTNUM which is not in the deck
terminate called after throwing an instance of 'std::logic_error'
  what():  MULTREGT record is based on region: MULTNUM which is not in the deck
Aborted

This could either be an issue with my deck or and issue with the parser. I'm not sure which one it is, I just wanted to report this problem.

**Comment by joakim-hove** [comment]
Fixed in: https://github.com/OPM/opm-parser/pull/430
