### ISSUE TITLE
ENPTVD table in eclipse state - some issues:

### ISSUE THREAD

**Issue by osae** [OPM/opm-parser#334]
a) Fully defaulted columns does not work (causes a throw in SingleRecordTable::applyDefaultsLinear) This essentially makes the functionality useless as defaulting one or more columns to signal default behavior is common procedure.

b) The look-up in the tables are triggered by the explicit appearance of the associated scaling keyword in the deck (e.g will not look for SWL in table unless SWL also appears as kw in the deck).  Again this renders the functionality essentially useless as standalone table is the rule rather than exception.

c) Also a few trivialities:
- EnptvdTable::init:   ParentType::applyDefaultsLinear not called for tag SWMAX
- GridPropertyEndpointTableLookupInitializer:   For SWU/ISWU selectValue is called with "SWCO" as tag instead of "SWMAX"

**Comment by joakim-hove** [comment]
Too old - please reopen if still relevant.
