### ISSUE TITLE
Packagin issues

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-parser#364]
issues discovered:
1) no doxy installed/generated
2) no pkgconfig file installed *
3) no cmake config mode files installed *
4) all libraries are unversioned *
5) libopm-json.so does not link to its dependencies (in particular libm) *
6) no debug symbols generated **
7) the only reason libParser.so does not conflict with something else is that nobody else has been fresh enough to grab such a general name. *
8) no end user applications (probably not an issue but i mention it).

    * show stopper issue in my opinion ** - not a showstopper - i just use the tools instead of manual objcopy as the other modules do.

**Comment by atgeirr** [comment]
I guess some of these issues might still be relevant, if so: which?

**Comment by notspiff** [comment]
all of these were addressed in the last round.

**Comment by akva2** [comment]
sigh. ^akva2
