### ISSUE TITLE
Change FaceDirEnum values such the *MINUS < *PLUS

### ISSUE THREAD

**Issue by blattms** [OPM/opm-parser#393]
The values are currently defined as:
```c++
enum DirEnum {
  XPlus  = 1,
  XMinus = 2,
  YPlus  = 4,
  YMinus = 8,
  ZPlus  = 16,
  ZMinus = 32
};
```
Is there a special (algorithmic) reason why {X,Y,Z}MINUS > {X,Y,Z}PLUS? For me this was kind of counter intuitive.

I am aware that one should not rely on these values, but in the rest of OPM it is the other way around.  E.g. For UnstructuredGrid faceTag is in [0, ..., 5] meaning [I-, I+, J-, J+, K-, K+]. Similar (+1) for CpGrid.

In the current situation translating the UG values to FaceDirEnum is
```c++
Opm::FaceDir::DirEnum faceDirection =
    Opm::FaceDir::DirEnum(1<<(faceTag-faceTag%2+(faceTag+1)%2));
```
which seems much uglier as for switched values (*MINUS<*PLUS):
```c++
Opm::FaceDir::DirEnum faceDirection =
    Opm::FaceDir::DirEnum(1<<faceTag);
```

If there is no special reason for the current situation I would propose to change to:
```c++
enum DirEnum {
  XMinus  = 1,
  XPlus = 2,
  YMinus  = 4,
  YPlus = 8,
  ZMinus  = 16,
  ZPlus = 32
};
```

**Comment by andlaus** [comment]
> Is there a special (algorithmic) reason why {X,Y,Z}MINUS > {X,Y,Z}PLUS? For me this was kind of counter intuitive.

No, as far as I know, there is no particular reason for this. Having said that, and as you commented yourself, relying on the numeric values of such enums is a mistake. If you want to avoid the uglyness of adding `switch` statements everywhere in opm-core, I'd propose to write a `dirEnumToFaceTag()` function which converts `DirEnum` to a `faceTag` as expected by `UnstructuredGrid`...

**Comment by dr-robertk** [comment]
As Markus pointed out, it should definitely be unique for UG, CpGrid, and the rest of OPM. 

It might be a good idea though to have the numbering as follows:

enum DirEnum {
  XMinus  = 0,
  XPlus = 1,
  YMinus  = 2,
  YPlus = 3,
  ZMinus  = 4,
  ZPlus = 5
};

Then you can use these values to access values stored in arrays instead of using switch case statements.

**Comment by andlaus** [comment]
> As Markus pointed out, it should definitely be unique for UG, CpGrid, and the rest of OPM. 

In some sense I agree: UG should use the `DirEnum` instead of the face tag concept. I disagree by defining `DirEnum` in such a way that it coincites with the face tag by "coincidence", though...

**Comment by dr-robertk** [comment]
I don't know about the face tage. I'm just saying that it is helpful if you could use these values to access arrays. On the other hand, what is the difference between DirEnum and faceTag? Aren't they used in the same way?

**Comment by joakim-hove** [comment]
The enum symbols are ordered according to "use order" - i.e. in this context `XPlus` is *way more common than `XMinus`. Apart from the obvious: "You should not rely on the numerical value of these enums" rant I have no objections to reordering.

The 2^n ordering indicates strongly that the values are used as bitmasks; the jury is still out on that question but my gut feeling now is that these enums are (no longer) used as bitmask and then a relabeling according to @dr-robertk would be a good ide.

**Comment by joakim-hove** [comment]
> [...] the jury is still out on that question but my gut feeling now is that these enums are (no longer) used as bitmask 

The jury has come back in; I looked at the wrong enum. The `FaceDir::DirEnum` enum is used to read the `MULTREGT` keyword which must support input like 'XZ' - i.e. the multiplier should be applied to faces 'X' and 'Z', so the 2^n structure must be intact, but I would be happy to implement the change originally suggested by @blattms.

**Comment by joakim-hove** [comment]
I'm closing this now; due to the need to support input like 'XZ' the 2^n structure must be retained.
