### ISSUE TITLE
Norne does not run

### ISSUE THREAD

**Issue by totto82** [OPM/opm-parser#396]
I get the following error when I run Norne (in opm-data/norne) with the updated parser.

Program threw an exception: Index must be smaller than 0 but is 0
terminate called after throwing an instance of 'std::out_of_range'
 what():  Index must be smaller than 0 but is 0
Aborted

I reset the wellCompletion commits but the error is still there. So I guess it is related to default values.

**Comment by totto82** [comment]
> I reset the wellCompletion commits but the error is still there. So I guess it is related to default values. 
Please ignore this last comment. I don't know if the error is due to the newest commits on wellCompletion or due to default values.

**Comment by joakim-hove** [comment]
Backtrace?
14. jan. 2015 09:48 skrev "Tor Harald Sandve" <notifications@github.com>
følgende:

**Comment by totto82** [comment]
I am able to run the reduced_norne deck with the full schedule. With shut completions etc. And so far I get a very good/perfect match with Eclipse. The reduced_norne case uses simplified fluids, no hysteresis, no relperm scaling etc. 

So the error can not be due to the wellCompletion PR. Maybe @andlaus can do some gitmagic to find the commit to blame.

**Comment by joakim-hove** [comment]
OK - I have it; fix coming.

**Comment by totto82** [comment]
Thanks. PR OPM/opm-core#721 indeed fixed the problem.
