### ISSUE TITLE
BHP limit for historical mode

### ISSUE THREAD

**Issue by totto82** [OPM/opm-parser#411]
From the manual: "For control modes other than BHP the BHP lower limit is automatically set to
atmospheric pressure when the well is first declared a history matching well (the first
time it appears in a WCONHIST keyword)." 

I don't think this is implemented. I.e. we allow for negative BHP.

**Comment by atgeirr** [comment]
What would be the best place to implement this? Somewhere, the (default, 1 atm) BHP control must be explicitly added. I guess the WellsManager class would be fine?

**Comment by totto82** [comment]
Fix provided in OPM/opm-autodiff#294.
