### ISSUE TITLE
Unit conversion error for GAS RESV limits

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-parser#419]
In `Schedule::handleWCONINJE()`, the rates are converted with the same routine and arguments for both the RATE (surface volume rate) target and RESV. For GAS injectors, this is wrong: RATE should be in MScf/day (with M meaning Mille, 1000, not Mega...) while RESV is in barrels/day. Both are however converted as if in MScf/day.

This *may* point to related bugs when using FIELD units, I have not checked that (Rs factors could be wrong as well, but I don't think they are or we would have failed long ago).

With SPE1, this leads to very touchy controls that are susceptible to random changing, as observed in OPM/opm-autodiff#300.

**Comment by andlaus** [comment]
does #421 help?

**Comment by atgeirr** [comment]
This is fixed now. I have not investigated if there are similar (in-code) conversion logic errors elsewhere, but I think after merging #421 and #422 this is probably ok.
