### ISSUE TITLE
Can't run NORNE anymore.

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-parser#486]
When I run the NORNE case I get the following exception: 

Program threw an exception: IOConfig: Reading GRIDFILE keyword from GRID section: Output of GRID file is not supported

This seems to happened in some file called IOConfig.cpp in opm-parser. All modules are at the latest state. Either the deck in opm-data needs an update or this might be a bug.

**Comment by GitPaean** [comment]
Please refer to the discussion in OPM/opm-parser#470

**Comment by dr-robertk** [comment]
I suggest that somebody with the proper knowledge fixes the code or the norne deck.

**Comment by joakim-hove** [comment]
> I suggest that somebody with the proper knowledge fixes the code or the norne deck.

The code has been fixed: https://github.com/OPM/opm-parser/commit/e7cbf7906629d7c857d4d0d55e02cd429b3ba492; I'll submit a PR adressing the Norne deck.

**Comment by dr-robertk** [comment]
Sounds good. Thanks.
