### ISSUE TITLE
Cannot run SPE3 on Jenkins

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-parser#487]
The following failure occurs:
```
Program threw an exception: OPM does not support the RPTRST BASIC=6 setting (write restart file every timestep)
```
I assume this has to do with a similar issue as #486, and hope that it can be reduced to a warning.

**Comment by joakim-hove** [comment]
> I assume this has to do with a similar issue as #486

The issue in this case is that the input setting `RPTRST BASIC=6` means that we ask for a restart file to be generated for every (simulator) timestep - that is not currently supported, and therefor we throw an exception. It should be `RPTRST BASIC=2` which means asking for a restart file every report step - I will create a opm-data pull request with that.

> and hope that it can be reduced to a warning.

Of course it can be reduced to a warning; but that is a political decision which I would like to discuss in a somewhat broader context. I feel I experience the following interaction between developers and consumers quite often:

- Developer: I want to enforce strict correctness - this particular situation I can handle correctly as requested and therefor I throw an exception.
- Consumer: Whatever - don't be so pompous  - just print a warning ehh?

I guess we all have both roles in this project - for this particular issue I am the developer.

**Comment by atgeirr** [comment]
You are correct, and it seems I have taken the user role here. Thinking a little more I now agree that we should not lightly reduce this to a warning, although I think it is *more ok* to reduce it to a warning if it is an output feature (as here) rather than a feature affecting the actual results. We are very far from supporting the full range of output features, and if we are going to throw on all of those we must delete most of the SUMMARY section in any deck we'd try I fear.

It is important that we restore our Jenkins runs quickly, but I agree that changing the data files is a good quick workaround.

**Comment by joakim-hove** [comment]
Have created: https://github.com/OPM/opm-data/pull/48

>We are very far from supporting the full range of output features, and if we are going to throw on all of those we must delete most of the SUMMARY section in any deck we'd try I fear.

Yes - you are obviously right, so we must find a suitable middle ground here.
