### ISSUE TITLE
Problems in IOConfig and KeywordGenerator

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-parser#501]
When I compile the latest master I get the following warnings:
```
/Users/atgeirr/opm-build-debug/opm-parser/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp:268:5: warning: control reaches end of non-void
      function [-Wreturn-type]
    }
    ^
/Users/atgeirr/opm-build-debug/opm-parser/opm/parser/eclipse/Generator/KeywordGenerator.cpp:105:26: warning: declaration shadows a local variable
      [-Wshadow]
            std::fstream stream(filename.c_str() , std::fstream::out);
                         ^
/Users/atgeirr/opm-build-debug/opm-parser/opm/parser/eclipse/Generator/KeywordGenerator.cpp:93:23: note: previous declaration is here
        std::ifstream stream(filename.c_str());
```
The IOConfig warning is serious: failing to return will usually give problems, in this case the function returns a bool, so there is no way for downstream code to tell it is invalid. I *cannot* fix this function since I do not know what it is intended to return.

The KeywordGenerator warning is probably less serious, but it should be taken care of: the variable name `stream` is used both for an input and an output stream, which is quite obfuscating. Other minor issues with that function include using non-const reference arguments and manually close()-ing a stream instead of letting the destructor do its job. I'll submit a fix for this function.

**Comment by chflo** [comment]
I have created a PR https://github.com/OPM/opm-parser/pull/503 for the IOConfig compiler warning, sorry for this mistake, the method overrideRestartWriteInterval should have return type void, not bool

**Comment by atgeirr** [comment]
No more warnings, great! Closing.
