### ISSUE TITLE
KeywordGenerator Build Error on GCC 4.4

### ISSUE THREAD

**Issue by bska** [OPM/opm-parser#509]
The implementation of [`KeywordGenerator::updateFile()`](https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/Generator/KeywordGenerator.cpp#L92) contains the following code
```C++
std::ifstream inputStream(filename);
```
in which `filename` is a `const std::string&`.  GCC 4.4 does not support a `std::basic_ifstream<>` constructor that takes a `std::string` so this statement results in build failures on that compiler.  The simple work-around is, of course,
```C++
std::ifstream inputStream(filename.c_str());
```

On a somewhat related note, the `KeywordGenerator:::updateFile()` method is declared as
```C++
bool KeywordGenerator::updateFile(const std::stringstream& newContent , const std::string& filename);
```
but the header file ([`KeywordGenerator.hpp`](https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/Generator/KeywordGenerator.hpp)) does not include `<sstream>` to declare `std::stringstream`.  This is okay, after a fashion, because `<sstream>` is transitively included through `ParserItem.hpp`, but it is still somewhat brittle.

**Comment by atgeirr** [comment]
> GCC 4.4 does not support a std::basic_ifstream<> constructor that takes a std::string so this statement results in build failures on that compiler

After a recent discussion on the mailing list the consensus was to end support for gcc 4.4 and allow features available in gcc 4.8. So almost all of C++11 is not acceptable for OPM code! In particular that includes the string constructor for the filestreams.

**Comment by bska** [comment]
> So almost all of C++11 is not acceptable for OPM code

Do you mean **now**?

**Comment by atgeirr** [comment]
> Do you mean now?

Yes. Statoil proposed changing this since they have completed their transition to a newer version of RHEL, and the only objection raised was that we should make sure we support Ubuntu 14.04 (which is why we settled on 4.8 and not 4.9).

**Comment by bska** [comment]
> Statoil proposed changing this since they have completed their transition to a newer version of RHEL

Very well.  I'll turn off my CentOS 5.11 builds since they're no longer needed.

**Comment by alfbr** [comment]
Our current environment is Red Hat 6.6 with the Developer Toolset (which contains the full gcc 4.9 toolchain). Basically it has been a wish from the Dune community that we finally were able to accommodate.

**Comment by bska** [comment]
> Our current environment is Red Hat 6.6 with the Developer Toolset 

I see.  CentOS 6 offers something similar, so maybe I'll just reinstall the reference server with the latest CentOS 6 release and get the toolset.  I won't be able to do that right away, however.
