### ISSUE TITLE
Number of timesteps - BASIC in RPTRST

### ISSUE THREAD

**Issue by larsblatny** [OPM/opm-parser#510]
Flow does not seem to produce any timesteps if setting BASIC = 1, 2 or 5 in RPTRST.
If BASIC = 4, the number of timesteps does not match the (desired) number of timesteps produced by Eclipse. 

However, when including FREQ = n, BASIC = 5 produce timesteps, but not the same number of timesteps as Eclipse.
In addition, if you do not specify FREQ = n, BASIC = 3 will result in the following from Flow: "Floating point exception (core dumped)".
In Eclipse, there will be no error/warning/problem/message if this is omitted (FREQ seems to be set to 1 by default).
If you include FREQ = n, BASIC = 3 will not result in the desired number of timesteps.

**Comment by atgeirr** [comment]
I am not sure this is (only) an opm-parser issue. Flow currently only supports writing output at report timesteps, and should warn or exit if anything other than that is required. This change has not yet been made, and for now it is the parser that checks for allowed values here.

The core dump may indicate a serious issue, and I will investigate that.

**Comment by alfbr** [comment]
Right now this is a major pain though. I am currently not able to get any report steps out of Norne.

**Comment by atgeirr** [comment]
My current Norne data set has this:

RPTRST
BASIC=2 KRO KRW KRG /

With BASIC=2 the current version should work.

**Comment by alfbr** [comment]
Are you getting any report steps in Resinsight?

**Comment by chflo** [comment]
Flow produces restart files for the different BASIC settings, but writes one more report step than eclipse, - report step 0. Resinsight then fails to open the (faulty).UNRST file properly, but as a temporary workaround one can leave out UNIFOUT from the data file, then the report steps will be displayed in Resinsight. 

When writing first report step for every year/month (BASIC=4/5),  due to the extra first report step, the offset becomes wrong and the report times for writing restart files becomes different in eclipse and flow.

I will look into this issue.

**Comment by joakim-hove** [comment]
Very good analysis of both @larsblatny and @chflo. 

>Flow produces restart files for the different BASIC settings, but writes one more report step than eclipse, - report step 0. Resinsight then fails to open the (faulty).UNRST file properly, 

I don't know the details here; possibly the output of the initial restart file for report step 0 is configured differently - and that we have got that wrong in opm-parser, but writing the solution for report step 0 amount to writing the inital state, and that is *not* generally a faulty thing to do. Or do you mean that the content of that step is faulty? This could maybe also (in addition ??) be an issue with Resinsights reading of report step 0?

**Comment by alfbr** [comment]
I don't think so, Resinsight reads files from Eclipse correctly.

**Comment by joakim-hove** [comment]
This is fixed in: https://github.com/OPM/opm-parser/pull/586
