### ISSUE TITLE
Using 'D' and 'E' when writing numbers on standard form

### ISSUE THREAD

**Issue by larsblatny** [OPM/opm-parser#514]
I don't know if this is very important, but I thought I should mention the following:
If you want to use scientific notation (i.e. writing numbers on standard form) in Eclipse, you can use the letter E (e.g. 0.000003 -> 3E-6). You can also use D (e.g. 3D-6), but this does not seem to be supported by Flow:
"Exception caught: Unable to parse string3.0D-6 to typeid: d"

**Comment by atgeirr** [comment]
This is a fortran vs C++ issue I think: D is accepted in Fortran's built-in converters but not in C++ (or C). If this is critical it would take some low-level stream hackery, but it could probably be done.

**Comment by bska** [comment]
> D is accepted in Fortran's built-in converters

Yeah, sort of.  It's really more of a requirement.  Fortran uses strictly typed floating-point literals throughout so `3.0D-6` is an (old-style) double precision literal whereas `3.0E-6` is a single-precision literal.  Modern Fortran uses kind numbers to convey the same information.  In C-derived languages all floating point literals are implicitly of type `double` unless modified by an `f` or `lf` suffix.

By the way, there is an edge case in Fortran's text representation of floating-point numbers so if the significand is one character too wide to fit in requested format, the IO system will drop the exponent marker and simply output the sign of the exponent.  This gives another answer to the age-old joke
```
1+1=10
```
