### ISSUE TITLE
About the keyword WELSEGS

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-parser#518]
Hi, all.

I have a few practical questions about the keyword WELSEGS, which will affect the implementation.

The keyword contains two parts. The first part is the definition about the top segment and some properties about the whole segment structure. Because the keyword can be input again after the first time (only the parts needed to be updated) for arbitrary times to update the segment structure, I would like to know in which way the segment structure can be updated later. 

The major question is that whether the first record (part) of the keyword will be changed in anyway when inputting the WELSEGS keyword for the second time. Since we always need to input the information for the first record whenever we input the keyword. Will it be reasonable to assume the information in the first record will never be changed when inputting the keyword for a second time after the first time. 

If the first record of the keyword can be changed, which items of the record can be changed. For example, will the location of the top segment node be changed? Will the way to input the tubing length and depth information be changed (INC or ABS)?  Will we get a new top segment and other segments remain unchanged or partly changed?

Thanks.

**Comment by joakim-hove** [comment]
Hello Kai;

I am still 90% offline - and have not thought/looked deeply about this, furthermore I must say that my first hand experience with these issues as a Eclipse user is limited. But anyway - my gut reaction when seeing a question like:

> [...] Will it be reasonable to assume the information in the first record will never be changed when inputting the keyword for a second time after the first time.

Is why do you ask - why bother? My very clear suggestion would be use the `DynamicState<T>` construction and internalize the full WELSEGS information as required. I think that will be the simplest, and the experience is *always* that everytime soneome one tries to make a simplifying  assumption about the Eclipse format it comes back to bite you.

**Comment by GitPaean** [comment]
Thanks for the good point. The original problem is that the length and depth values can be given either in incremental `INC` way or absolute  `ABS` way. When given with a range (N1 ... N2 segments), some values are not determined immediately. A processing will always be required to make the property values complete. I just felt it was a little messy when values are given in one way first, then updated in the other way. Especially, when the values are given in a mixed way, and the top segment location is changed, it will cause even a bigger mess. 

Anyway, I saw your point. To achieve the full flexibility, probably we should keep a copy of all the input information in its original way. And then every time any update occurs, we update this copy first. Then we always do a post-processing based on this copy to get the information we need for simulator. I am not sure if this is the way Eclipse works, while I assume it should be the user's responsibility to handle the logic of the segment structures. 

The problem about this way is that when a segment is given a part of the range. For example, the segment `N2` was given in the range `N1....N3`. With the original input, the information about the `N2` is not clear without processing. Then if we update segment `N2` segment separately later, some logical problem will happen there. 

The cases will can see now are basically very simple and logical ones. And it will be user's responsibility to make sure the segment structures are well defined. I am not sure Eclipse will handle or users will make very difficult or confusing cases. 

Comments will be much appreciated anytime. Thanks.

**Comment by joakim-hove** [comment]
This seems kind of open ended - closing now.
