### ISSUE TITLE
Problem with the 'Total' (cumulative) quantities 

### ISSUE THREAD

**Issue by larsblatny** [OPM/opm-parser#523]
I am not sure if this issue belongs in opm-parser, please let me now if it should be posted somewhere else.

By studying graphs produced by Flow and Eclipse, I notice that the 'cumulative quantities' produced by Flow are not consistent with the corresponding output from Eclipse. By 'cumulative quantities', I mean quantities such as WOPT, WGPT, WOIT, etc..., those ending with 'T' ('T' for 'Total'). Could there be something wrong with how these are implemented in OPM/Flow?

The files I have been studying, and which all behave as described above, are:
```
SPE1DECK.DATA         at opm-data/spe1
SPE1CASE2.DATA        at opm-data/spe1_new
SPE3CASE1.DATA        at opm-data/spe3_new
SPE3CASE2.DATA        at opm-data/spe3_new
SPE3_MODIFIED.DATA    at opm-data/spe3
```
Note 1: All not ending with 'T' produced by Flow are consistent with those produced by Eclipse (one exception in SPE3).
Note 2: There are a few 'T'-graphs produced by Flow that are consistent with Eclipse, but these are identically zero (as a function of time).

**Comment by joakim-hove** [comment]
This is fixed here: https://github.com/OPM/opm-core/pull/889
