### ISSUE TITLE
the definition of the thickness of grid block

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-parser#529]
Hi, I need the information of the thickness of grid block in the direction of the well penetration. 

I am wondering how we define them sine the grid blocks are not rectangular typically. Should we calculate the size of the bounding box and use the size information (`DX, DY or DZ`)of the bounding boxes?

Thanks.

**Comment by joakim-hove** [comment]
Hello;

the thickness in the z-direction is available as the (brand new) method `EclipseGrid::getCellThickness()` - that is based on an existing ert function: https://github.com/Ensembles/ert/blob/master/devel/libecl/src/ecl_grid.c#L4295.

Something similar for the other directions is of course trivial to add?

**Comment by qilicun** [comment]
Hi, @joakim-hove 
Does ERT-python has a same function related to the grid  cell thickness?

**Comment by joakim-hove** [comment]
> Does ERT-python has a same function related to the grid cell thickness?

Yes : `EclGrid.cell_dz()`

**Comment by joakim-hove** [comment]
This does not seem relevant any more - closing.

**Comment by GitPaean** [comment]
Sorry for not getting back to this sooner. If I want to add the thickness also for x and y direction, where I should begin with? Should I add a function in Ert first then opm-parser? Thanks.

**Comment by joakim-hove** [comment]
> Should I add a function in Ert first then opm-parser?

I guess that is the natural way to do it. I would be happy to implement this in ert and opm-parser; however due to rotations+++ the approach used for dz is not trivially generalized to dx and dy. 

I guess the natural definition would be something like: "dx - the average 'thickness' of the cell in the \hat{i} direction"?

**Comment by GitPaean** [comment]
Yes. That is the definition I want to try. 

I was looking at the code, while I am not familiar with the order of the `corner_list`.  It will be great if you can help to implement that. 

Thanks.

**Comment by GitPaean** [comment]
I am wondering if there is any update. Thanks.

**Comment by joakim-hove** [comment]
> I am wondering if there is any update.

Sorry - had completely forgotten; hopefully this week.

**Comment by joakim-hove** [comment]
Does this look ok: https://github.com/OPM/opm-parser/pull/652

Can of course easily change the API if that would be convenient. Observe that this can not be tested before the ERT PR: https://github.com/Ensembles/ert/pull/976 has been merged.

**Comment by GitPaean** [comment]
Thanks. It looks good to me right  now. I will run some tests with the examples that I think the calculation of the cell thickness matters later.

**Comment by GitPaean** [comment]
With the examples I have concern with, the preliminary test did not show any difference in results compared with the old way to calculate the cell thickness based on bounding box `WellsManagerDetail::getCubeDim`. Examples with much more twisted grids probably will be required to tell which way is the correct way or the better way. 

I think the PR #652 is good and should go in for future use. And it can reduce some replicated code in the fully implicit black oil polymer module. 

I will close the issue for now. Thanks for the efforts.
