### ISSUE TITLE
Undefined behaviour in `bool TimeMap::isTimestepInFreqSequence()`

### ISSUE THREAD

**Issue by bska** [OPM/opm-parser#595]
The member function
```C++
bool TimeMap::isTimestepInFreqSequence(size_t timestep, size_t start_timestep, size_t frequency, bool years) const
```
which is defined in [`opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp`](https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp#L251) contains the following statement on [line 274](https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp#L274)
```C++
int dist = std::distance( ci_start_timestep - 1, ci_timestep );
```
with `ci_start_timestep` and `ci_timestep` both being positions (iterators) into a collection, `timesteps`.

The above statement is undefined if `ci_start_timestep` happens to be equal to `timesteps.begin()`, because we are generally not allowed to form the iterator `begin() - 1` of any collection.  The test `runIOConfigIntegrationTest` triggers this undefined behaviour and libstdc++'s Debug Mode produces a diagnostic of the form
```
/usr/include/c++/4.6/debug/safe_iterator.h:307:error: attempt to retreat a 
    dereferenceable (start-of-sequence) iterator 1 steps, which falls     
    outside its valid range.
```

I don't know what the correct solution is in this case because I don't know the code in question.  I only know that this issue may cause problems in the future.

**Comment by akva2** [comment]
int dist = std::distance(ci_start_timestep, ci_timestep)+1 should be 
entirely equivalent right?

**Comment by bska** [comment]
>
```C++
int dist = std::distance(ci_start_timestep, ci_timestep)+1
```
should be entirely equivalent right?

Yes, I think you're right.
