### ISSUE TITLE
WAT or WATER

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-parser#639]
I'm running some cases that in the well configuration,  the phase name is input as WAT not WATER 不but OPM will throw. since lots of the reservoir engineers could use WAT instead of WATER, ECLIPSE can recognize it and run without any issue. So could opm-parser behavior the same with ECLIPSE at this matter to reduce some unnecessary modification to the origin  DATA files.

**Comment by joakim-hove** [comment]
Yes - exactly which keyword(s)?
27. nov. 2015 06:17 skrev "Liu Ming" <notifications@github.com> følgende:

**Comment by qilicun** [comment]
>Yes - exactly which keyword(s)?

like GCONINJE

**Comment by andlaus** [comment]
sounds like we need this. I have two questions:

- is there a good way to find out which keywords and which items support this?
- can an arbitrary unique prefix also be used? (e.g. 'WA' or 'WATE')

**Comment by joakim-hove** [comment]
I hope/think this can be fixed by only modifying the relevant ScheduleEnums
string conversion method.
27. nov. 2015 09:43 skrev "Andreas Lauser" <notifications@github.com>
følgende:

**Comment by joakim-hove** [comment]
> can an arbitrary unique prefix also be used? (e.g. 'WA' or 'WATE')

Good question - I do not know; my intention was to just accept 'WAT'

**Comment by joakim-hove** [comment]
Will you try now - after merging: https://github.com/OPM/opm-parser/pull/640

**Comment by qilicun** [comment]
@joakim-hove 

I tested, it works, thanks!
