### ISSUE TITLE
About the input of the permeability

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-parser#645]
I am not sure if this should be in parser or autodiff. 

The following input of permeability will fail in Eclipse with error `INSUFFICIENT DATA TO COMPUTE Y TRANSMISSIBILITIES` (following the discussion OPM/opm-data#83, I am not 100% sure) while it works for OPM.  People have access to Eclipse can help to verify. 

My question is, with the following input, what is the permeability in the y direction in OPM. 

```
PERMX
100*221.009415 /
PERMX
100*221.009415 /
PERMZ
100*22.00 /
```

**Comment by bska** [comment]
> My question is, with the following input, what is the permeability in the y direction in OPM.

In this particular case the `PERMX` property will be copied to `PERMY`.  See function [`fillTensor()`](https://github.com/OPM/opm-core/blob/master/opm/core/props/rock/RockFromDeck.cpp#L291-L350), called from `RockFromDeck::assignPermeability()`, in [`opm/core/props/rock/RockFromDeck.cpp`](https://github.com/OPM/opm-core/blob/master/opm/core/props/rock/RockFromDeck.cpp).  This is a conscious design decision that simplifies the transmissibility calculation.

**Comment by GitPaean** [comment]
I am not sure how this simplifies the transmissibility calculation.  On the other side, it will make some input error not reported or warned by the simulator. 
For example, when PERMX and PERMY are intended to be different, while a typo was made there. 
```
PERMX
100*220/
PERMX
100*120 /
PERMZ
100*22.00 /
```
The OPM just will run and give a run results without reporting an error or warning.

**Comment by atgeirr** [comment]
I think that we should support only giving PERMX, as that is how to support scalar permeabilities.

However, if PERMZ exists, we should require PERMY as well, since that is a probable error. I expect this can be easily fixed.

**Comment by joakim-hove** [comment]
> My question is, with the following input, what is the permeability in the y direction in OPM.

The `GridProperties<T>`container will autocreate the keyword when asked for it: https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/Grid/GridProperties.hpp#L76

The autocreate process will then run the default initializier of the keyword, when it comes to `PERMY`that is here: https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/EclipseState.cpp#L863 - i.e. it will initialize with `nan`.

So as seen from `opm-parser` this will return `PERMY` equal to `nan`. The processing further down the chain?

**Comment by bska** [comment]
> I am not sure how this simplifies the transmissibility calculation.

Because we can rely on the tensor being complete and not have to check which components are present.

**Comment by joakim-hove** [comment]
> In this particular case the PERMX property will be copied to PERMY

Essentially ignoring `PERMY` completely?

**Comment by bska** [comment]
>> In this particular case the PERMX property will be copied to PERMY
>
> Essentially ignoring PERMY completely?

If `PERMY` is not present, then we use `PERMY` = `PERMX`.  If `PERMY` **is** present, then we use that data instead.

**Comment by atgeirr** [comment]
> If PERMY is not present, then we use PERMY = PERMX. If PERMY is present, then we use that data instead.

... and this is precisely what we should change: if neither PERMY nor PERMZ is present, use PERMX, otherwise both must be present.

**Comment by atgeirr** [comment]
I realized now that this discussion is in opm-parser, while the implementation in question is in opm-core (opm/core/props/rock/RockFromDeck.cpp, function fillTensor()). That code is older than the parser, and possible could be rewritten in a simpler form now, but in any case that is where this problem must be handled.
