### ISSUE TITLE
What the following cmake message means?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-parser#668]
```
-- Performing Test HAVE_OPM_COMMON
-- Performing Test HAVE_OPM_COMMON - Success
-- opm-common_DIR = opm-common_DIR-NOTFOUND
-- Could NOT find opm-common (missing:  opm-common_LIBRARY) 
```
Anything can cause problem happens here?

Thanks.

**Comment by joakim-hove** [comment]
Hmm - means I must fix something!
2. feb. 2016 15:54 skrev "Kai Bao" <notifications@github.com> følgende:

**Comment by joakim-hove** [comment]
Hmm;

I think the problem is that you have not built the opm-common library; as of this: https://github.com/OPM/opm-common/pull/66 you must actually *build* the opm-common.

**Comment by GitPaean** [comment]
Actually, I built opm-common in opm-common-build.

**Comment by joakim-hove** [comment]
> Actually, I built opm-common in opm-common-build.

OK - can you go in there and check if a `libopmcommon.(a|so)` has been created?

**Comment by GitPaean** [comment]
yes. 
```
kaib@kaib-WS ~/OPM/debug/opm-common-build $ find . -name "libopmcommon*"
./lib/libopmcommon.la
./lib/libopmcommon.a
```

**Comment by GitPaean** [comment]
The building of the opm-parser was passed, while the building the opm-material got the problem. OPM/opm-material#116  . I was looking for the reason, and I am not sure if this will cause the problem. 

The building of other repos is okay on your side?

**Comment by joakim-hove** [comment]
> The building of other repos is okay on your side?

Yes; but that might just be the venerable *works for me*? Got to go now - but can look more into this tomorrow if required.

**Comment by GitPaean** [comment]
Sure. No problem. If the building of OPM repos is OKay for other people, I must do something wrong on my side.

**Comment by akva2** [comment]
make sure to configure in clean directories (i.e. do not reconfigure and old 'build' dir).

**Comment by GitPaean** [comment]
Yes. I cleaned the build directory.

**Comment by GitPaean** [comment]
A more complete version is here

```
 65 -- Could NOT find CJSON (missing:  HAVE_CJSON) 
 66 -- Checking whether the file system is case-sensitive
 67 -- File system is case-sensitive
 68 -- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
 69 -- Failed to find library "opmcommon" for module opm-common
 70 -- Finding package C99 using module mode
 71 -- Performing Test HAVE_C99
 72 -- Performing Test HAVE_C99 - Success
 73 -- Found C99: -std=c99  
 74 -- Performing Test HAVE_OPM_COMMON
 75 -- Performing Test HAVE_OPM_COMMON - Success
 76 -- opm-common_DIR = opm-common_DIR-NOTFOUND
 77 -- Could NOT find opm-common (missing:  opm-common_LIBRARY) 
```
