### ISSUE TITLE
Recognize WAT for WATER in WELSPECS etc.

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-parser#685]
(sorry for initial message empty, accidentally hit return key...)

The strings used in WELSPECS etc to specify phase are apparently often shortened in practical use. Perhaps we should support that?

**Comment by joakim-hove** [comment]
Hmmm - actually the `PhaseEnumFromString()` function: https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp#L289 already seems to accept `'WAT'` - but maybe the callsite you are referring to is not using that function? Happy to update.

**Comment by joakim-hove** [comment]
Any updates on the offending callsite?

**Comment by atgeirr** [comment]
I am not sure of the call site, will try to figure this out.

**Comment by joakim-hove** [comment]
Closing this?

**Comment by atgeirr** [comment]
Have not been able to substantiate this further, will close (and reopen if necessary).
