### ISSUE TITLE
config.h does not get generated

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-parser#71]
the "config.h" file is not generated using the current build system. I suspect that is the reason why I get the following error when trying to compile the unit tests under some circumstances:

```
Linking CXX executable ../../../runjsonTests
cd /home/and/src/opm-parser/opm/json/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/runjsonTests.dir/link.txt --verbose=1
/usr/bin/clang++   -pipe -Wall -Wno-unknown-pragmas -std=c++0x -g   -O0 -DDEBUG  -ggdb3    CMakeFiles/runjsonTests.dir/jsonTests.cpp.o  -o ../../../runjsonTests -rdynamic ../libopm-json.a -lboost_filesystem-mt -lboost_date_time-mt -lboost_system-mt -lboost_unit_test_framework-mt ../libcjson.so -lboost_filesystem-mt -lboost_date_time-mt -lboost_system-mt -lboost_unit_test_framework-mt -Wl,-rpath,/home/and/src/opm-parser/opm/json 
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/crt1.o: In function `_start':
/home/abuild/rpmbuild/BUILD/glibc-2.18/csu/../sysdeps/x86_64/start.S:118: undefined reference to `main'
clang-3.3: error: linker command failed with exit code 1 (use -v to see invocation)
```

(at least, a forgotten `#include "config.h"` was the cause for this error last time in a different module.)

**Comment by atgeirr** [comment]
I still don't see a config.h in my opm-parser build dirs, but I do not think that is as long as #defines such as HAVE_MPI, HAVE_NULLPTR, etc. are not used in the code. The HAVE_DYNAMIC_BOOST_TEST however was responsible for trouble earlier in other modules, and I am not sure if (or why not) it is necessary in opm-parser too. All boost test-using test programs in other modules do this:
```
#if HAVE_DYNAMIC_BOOST_TEST
#define BOOST_TEST_DYN_LINK
#endif
```
This block is not present in some opm-parser tests I looked at just now. Are we just lucky that it works?

**Comment by jokva** [comment]
This seems stale. Reopen if this is a problem.
