### ISSUE TITLE
 Recognize WAT for WATER in WELSPECS etc. #685 Closed atgeirr opened this Issue Feb 15, 2016 · 5 comments

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-parser#722]
I'm sorry for not getting back earlier the offending keyword is:

-- INJECTION WELL CONTROLS                                                      
--                                                                             
-- WELL   FLUID   OPEN/  CNTL  SURF   RES    BHP   THP   VFP               
-- NAME   TYPE    SHUT   MODE  RATE   RATE   PRSES PRES  TABLE             
WCONINJE                                                                        
'WI*'    'WAT'   'SHUT' 'RATE' 5000   1*     4000   1*    1*                   /
/

and the error dump is:

---------------    Reading parameters     ---------------
deck_filename found at /, value is SPE9-WATER01.DATA
output not found. Using default value 'true'.
output_dir not found. Using default value 'output'.
Failed to create valid ECLIPSESTATE object. See logfile: output/LOGFILE.txt
Exception caught: Unknown enum state string: WAT
baxendaled@baxendaled-VirtualBox:~/opm-data-master/Course$

**Comment by atgeirr** [comment]
We have identified the cause of the problem. We will change it to allow WAT.
