### ISSUE TITLE
Exception caught: Expected double, got: '-0.000'

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-parser#740]
I have some data file, when I use relpermDiagnostics and flow, the program threw an exception: Expected double, got: '-0.000'.  The message comes from ``opm-parser/opm/parser/eclipseRawDeck/StarToken.cpp`` I guess this due to new changes in opm-parser recently, because at least in Feb, relperm diagnostics works very well with these data files.

**Comment by joakim-hove** [comment]
Ok.- If the filer can be shared please post av a gitt,  otherwise a private email.

**Comment by qilicun** [comment]
>If the filer can be shared please post av a gitt, otherwise a private email.
I'm not sure, the data is used to test relpermDiagnostics from Alf, I think @alfbr could comment on this.

**Comment by joakim-hove** [comment]
OK; no need to send anything; we will fix it.

It looks like the `std::atof()` code in `readValueToken()` actually can not read 0.0000! I guess we should use `std::strtod()` instead.

**Comment by qilicun** [comment]
Why not ``std::stod()``?

**Comment by joakim-hove** [comment]
Hmmm - strod will not work with the string_view.  We will fix IT.

**Comment by jokva** [comment]
>  It looks like the std::atof() code in readValueToken() actually can not read 0.0000! I guess we should use std::strtod() instead.

It can, but because it's a C function it also uses 0.0 to signal a possible broken value. This error is in the slow path check to verify that it wasn't a malformed number but rather actually zero (which doesn't account for preceding +/-.

**Comment by jokva** [comment]
@qilicun Could you please apply and  test https://github.com/OPM/opm-parser/pull/741?

**Comment by qilicun** [comment]
fixed by https://github.com/OPM/opm-parser/pull/741
