### ISSUE TITLE
Replace OpmLog with MessageContainer in Parser

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-parser#754]
With https://github.com/OPM/opm-parser/pull/752 was merged, replace OpmLog with MessageContainer is the next step. The situation is that both Deck and EclipseState has a MessageContainer instance, the question is how to to use MessageContainer for those which is under the EclipseState directory, like, Schedule, Grid? The reason is that you can't create an EclipseState object in those classes. Do you have any ideas?

**Comment by jokva** [comment]
Several possible solutions, but the simplest one would be to have an internal message container for each of them, which will then be populated by the respective object. These can easily be accumulated from caller when needed, possibly aided by a function or two (they're monoids and I am considering proposing some high level functions (using iterators) that will give us easy access to the sum of a bunch of containers).

**Comment by atgeirr** [comment]
I think that idea sounds good, just having a simple `MessageContainer::appendMessages(const MessageContainer&)` method would be enough to collect the messages higher up in a simple way (unless call/message ordering is more messy than I think).

**Comment by jokva** [comment]
If temporal message ordering turns out to be very important (maybe, but my gut feeling says no) or other ordering that isn't grouping by source file or so, we can always add more metadata.

**Comment by joakim-hove** [comment]
>  the question is how to to use MessageContainer for those which is under the EclipseState directory, like, Schedule, Grid?

Well - as I see it there are two alternatives;

1. Adding a MessageContainer object to the various subobjects, like `Schedule`.
2. Pass a reference to the `EclipseState` messagecontainer around to the various other constructors.

I have a small preference for the first alternative; in that case I would assume the following sub objects should get an internal `MessageContainer`: `Schedule, TableManager, Eclipse3DProperties` and `EclipseGrid`? And of course of `MessageContainer::addMessages( const MessageContainer& )`must be implemented.

Please wait with this until: https://github.com/OPM/opm-parser/pull/751 is merged.
