### ISSUE TITLE
Difficult api: EclipseDeck?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-parser#795]
The seemingly quite simple PR: https://github.com/OPM/opm-upscaling/pull/188 is an example of a recurring problem:
1. The `Deck` datatype is essentially a quite simple container of `DeckKeyword` instances, the `Deck` container gives no upfront guarantees of the content of the container.
2. The `EclipseState` constructor requires a valid[1] deck as input, and will raise an exception if e.g. the `GRID` section is missing.
3. The `EclipseGrid( Deck )`constructor is by construction accepts a non valid grid - in particular a grid without a `GRID` section.

We therefor have a situation where the two constructors:

``` C++
EclipseGrid::EclipseGrid( Deck ) 
...
EclipseState::EclipseState( Deck, )
```

have different semantic requirement to the input argument - that is quite difficult to see!

**EclipseDeck**

As a possible improvement I suggest that we create a class e.g. `EclipseDeck` which wraps/extends an existing `Deck` instance and enforces deck validity in the constructor:

``` C++
EclipseDeck::EclipseDeck( const Deck& deck) {
    if (!deck.hasKeyword("GRID"))
      throw std::invalid_argument("Missing GRID section");
   ...
}
```

By using the `EclipseDeck` or `Deck` type in the api we can clearly communicate whether we want a semantically correct Eclipse deck, or just a random collection of keywords.

[1]: Valid is quite poorly defined in this context, but it at least requires some sections. Going along the suggested route with `EclipseDeck` we could also give a much better definition to _valid deck_.

**Comment by andlaus** [comment]
couldn't these "correctness requirements" be simply folded into the parseMode with EclipseState doing the parser creation and deck parsing internally?

also, IMO it would be beneficial if `EclipseState` would provide a `getDeck()` method: it seems to be a common pattern in C++ that higher-level classes provide a "I-know-what-I'm-doing,-give-me-the-low-level-stuff-in-all-its-gory" method; e.g. std::sting::c_str() and std::sting::data(). why should `EclipseState` stay different in that respect?

**Comment by joakim-hove** [comment]
> couldn't these "correctness requirements" be simply folded into the parseMode with EclipseState doing the parser creation and deck parsing internally?

Well  - for the foreseeable future I think we will need to support raw `Deck` access in addition to `EclipseState`access, and then the purpose of my loose suggestion was to get compile time differentiation between a "strictly correct" `Deck` and just-a-random-collection-of-keywords `Deck`. However - I certainly agree that the `ParseContext` should be right place to configure exactly what constitutes a valid `Deck`. 

> IMO it would be beneficial if EclipseState would provide a getDeck()

Yes - that is in the pipeline.

**Comment by andlaus** [comment]
> and then the purpose of my loose suggestion was to get compile time differentiation between a "strictly correct" Deck and just-a-random-collection-of-keywords Deck

why do you think it is beneficial to force this this at compile time? as far as I see, a "correct deck" looks the same as an incorrect one from the API perspective? I think it would be good if just the "aspects of interest" of the deck could be forced to be correct, but a `EclipseDeck` would be an all-or-nothing approach...

**Comment by joakim-hove** [comment]
> as far as I see, a "correct deck" looks the same as an incorrect one from the API perspective? 

Yes - that is correct. The whole point of my suggestion was to change that - so that it would be possible to distinguish between a "strictly valid" and "bunch-of-keywords" `Deck` in the API.

**Comment by andlaus** [comment]
> The whole point of my suggestion was to change that - so that it would be possible to distinguish between a "strictly valid" and "bunch-of-keywords" Deck in the API.

Yeah, I got that. my question was rather: From a user's perspective, what's the difference between "collection of random keywords" and "collection of random keywords which adhere to a bunch of random 'correctness' properties"? wouldn't it be better leave the deck a container of random keywords and provide "validator" classes/functions which can check if the deck conforms to a given "correctness property"?

**Comment by joakim-hove** [comment]
> wouldn't it be better leave the deck a container of random keywords and provide "validator" classes/functions which can check if the deck conforms to a given "correctness property"?

OK - I see; you might be right. No code written yet.

**Comment by alfbr** [comment]
An API improvement here is welcome, but I am not sure we should prioritise this now. We are still desperately missing output functionality, including API design related to output.

**Comment by atgeirr** [comment]
To me the EclipseState *is* the validated and curated deck, and the Deck is the raw thing. I do not think that the requirements placed on the Deck (passed as constructor arguments to EclipseState) necessarily make sense to represent outside the EclipseState class (at least not all of them).

I do not really see a big problem here as long as we enforce the following policy: if you use EclipseState you must use the EclipseGrid from there and not construct it directly from the deck. I don't think there is an easy way to make the compiler enforce this though, so instead we should make it easy to avoid by making an EclipseState constructor that takes the filename and parse context, accessing the Deck if needed by a `getDeck()` method, but usually not explicitly constructing the Deck or Parser at all.

**Comment by joakim-hove** [comment]
> I do not really see a big problem here as long as we enforce the following policy [...]

Well - we have a conflicting situation:

1. The preferred&trade; way is to create an `EclipseState` and extract e.g. grid from there. The `EclipseState` constructor requires a valid deck with all sections.
2. We insist on the ability to create a grid based on naked keywords from the `GRID` section; such a deck will blow up the `EclipseState` constructor. There is no way to detect this compile time.

Since alternative 1 is the preferred approach I fear that supporting 2) will repeatedly create problems of this kind: https://github.com/OPM/opm-upscaling/pull/188#issuecomment-216881055 

> so instead we should make it easy to avoid by making an EclipseState constructor that takes the filename[....]

I agree that we should make such a constructor. But real problem here is with limited input decks which can not be used to instantiate an `EclipseState` at all.

I'll leave it for now.

**Comment by andlaus** [comment]
> - We insist on the ability to create a grid based on naked keywords from the GRID section; such a deck will blow up the EclipseState constructor. There is no way to detect this compile time.

[...]

> I agree that we should make such a constructor. But real problem here is with limited input decks which can not be used to instantiate an EclipseState at all.

why not simply allow to instantiate `EclipseGrid` using a constructor that takes the deck? In some cases the rest of `EclipseState` will simply blow up anyway. (Note that the same applies to the PVT Tables, NNCs, the schedule, etc.) This would mean that `EclipseState` is seen as a "collection of its parts": If you only need some of these parts, there's no need to jump through hoops in the deck but you need to instantiate the higher level objects manually.

**Comment by OPMUSER** [comment]
I missed this earlier but ACTNUM is not required for a valid deck it is 
optional. On simple models, like the SPE comparison decks , there will 
be no ACTNUM keyword.
ThunderBird Signature File

Regards, David Baxendale Email: David.Baxendale@gmail.com

------------------------------------------------------------------------

**Comment by jokva** [comment]
This issue is stale and largely addressed, or in the more-or-less immediate pipeline.
