### ISSUE TITLE
Failure to parse RPTRST?

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-parser#799]
The pinch processor test in opm-core reads a test file that contains this part:
```
RPTRST
  BASIC=3  -- restart data written every FREQ time
  FREQ=10  -- save every 10th report time
  PCOW
  TRANX
  TRANY
  TRANZ
/
```
Currently I get a bad cast (from lexical_cast on Schedule.cpp line 1208) at the BASIC=3.

I assume this is an opm-parser issue since there were no opm-core changes I am aware of that changed this.

**Comment by jokva** [comment]
On it.
