### ISSUE TITLE
Running Model 2

### ISSUE THREAD

**Issue by totto82** [OPM/opm-parser#803]
With the current master I am no able to parser Model 2. I just get: 

     Program threw an exception: Not a data keyword ?

What does this message mean?

**Comment by pgdr** [comment]
PR #801 should have changed that error message, and we believed #800 fixed this issue (for now).

Are you on latest?  Specifically, do you have commit _Ignore RPTONLY_?

**Comment by pgdr** [comment]
It works here. :)

I haven't run the entire simulation, but it's now simulating at my computer.

**Comment by totto82** [comment]
With #801, I get the more informative 

    Program threw an exception: Not a data keyword "WNEWTON"?

Removing WNEWTON does the trick.

**Comment by jokva** [comment]
Better fixes to these issues is in the pipeline.

WNEWTON is a keyword ert reports as a keyword that should print a well-related value, when in fact it is related to the number of iterations taken in the last newtonian iteration.

**Comment by joakim-hove** [comment]
>WNEWTON is a keyword ert reports as a keyword that should print a well-related value, when in fact it is related to the number of iterations taken in the last newtonian iteration.

OK - this is a summary variable, which does not follow the normal naming rules, so this should be special cased in ert. On it.

**Comment by joakim-hove** [comment]
OK - with https://github.com/Ensembles/ert/pull/1082 in the `WNEWTON` keyword should be accepted (although not *handled* properly).
