### ISSUE TITLE
VS2015 : Unit tests failing

### ISSUE THREAD

**Issue by magnesj** [OPM/opm-parser#825]
The following unit tests fails on VS2015
```
DirectorySort
parse_fileWithENDINCKeyword_deckReturned
parse_fileWithENDKeyword_deckReturned
parse_fileWithPathsKeyword_IncludeExtendsPath
parse_fileWithWWCTKeyword_deckReturned
Verify_find_includes_Data_file_has_include_file_that_again_includes_a_symlink
Verify_find_includes_Data_file_has_include_that_is_a_symlink
Verify_find_includes_Data_file_is_a_symlink
```

I think part of the problem is related to relative paths on Windows

**Comment by jokva** [comment]
We'll look into this asap. Thanks!

**Comment by joakim-hove** [comment]
These:

>```
Verify_find_includes_Data_file_has_include_file_that_again_includes_a_symlink
Verify_find_includes_Data_file_has_include_that_is_a_symlink
Verify_find_includes_Data_file_is_a_symlink
```

should be fixed with: https://github.com/OPM/opm-parser/pull/827

**Comment by jokva** [comment]
https://github.com/OPM/opm-parser/pull/873

This PR should fix the rest of the failing unit tests. Mind testing it?

**Comment by magnesj** [comment]
Tested and works as expected. Good work!
