### ISSUE TITLE
Is keyword OPERATE supported?

### ISSUE THREAD

**Issue by magnesj** [OPM/opm-parser#838]
We have a test case produced by @hhgs we have used many times in ResInsight testing.

In this model there is a section using the `OPERATE` keyword, and I could not see that this is supported. If not, when is this keyword planned to be supported?

Example use
```
-------------- IRREDUCTIBLE WATER SATURATION --------------------
OPERATE
SWL    6* MULTX  PERMX 1.E10       / Temp:  SWL=1.E10*PERMX
SWL    6* MINLIM SWL   1.0         /
SWL    6* LOG10  SWL               / Temp:  SWL=log(1.E10*PERMX)
SWL    6* MULTA  SWL   -0.06  0.91 / Final: SWL=0.31-0.06*log(PERMX)
--SWCR 6* COPY   SWL               / SWCR=SWL
SWCR   6* MULTA  SWL   1.0    0.0  / SWCR=SWL+0.0 (+0.3)
SWCR   6* MAXLIM SWCR  0.7         / max(SWCR)=0.7
SGU    6* MULTA  SWL   -1.0   1.0  / SGU=1-SWL
/
```

**Comment by alfbr** [comment]
You should be able to use the unknown keyword parsecontext for that. We have currently no plans for implementing it, but do you even need it?

**Comment by joakim-hove** [comment]
>In this model there is a section using the OPREATE keyword, and I could not see that this is supported.

No that is not supported.

>If not, when is this keyword planned to be supported?

Frankly I had never seen that keyword before; but I think it should not be to difficult to support it.

**Comment by OPMUSER** [comment]
Yes, this is a frequently used keyword to manipulate the data in Eclipse
for those who are not using Petrel RE. I use it in about 50% of my models.
Engineers with ready access to Petrel RE are more likely to do this type of
data transform in Petrel and and then export the resulting property.

On Tue, Jun 14, 2016 at 4:28 PM, Joakim Hove <notifications@github.com>
wrote:

> In this model there is a section using the OPREATE keyword, and I could
> not see that this is supported.
>
> No that is not supported.
>
> If not, when is this keyword planned to be supported?
>
> Frankly I had never seen that keyword before; but I think it should not be
> to difficult to support it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OPM/opm-parser/issues/838#issuecomment-225813612>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ARIID1c5Dp5VC3g8xJaoD3Z7bJQ6yue0ks5qLmYmgaJpZM4I1C8R>
> .
>



-- 
Regards

David Baxendale
david.baxendale@gmail.com

**Comment by magnesj** [comment]
@alfbr I use the unknown keyword parsecontext, but it is not working as expected. Parsing throws exception and says it found `SWL`. It looks like the case has nested keywords, is that supported by the unknown keyword parsecontext?

**Comment by joakim-hove** [comment]
>  I use the unknown keyword parsecontext, but it is not working as expected. Parsing throws exception and says it found SWL. It looks like the case has nested keywords, is that supported by the unknown keyword parsecontext?

OK - this should work; so although I guess we will eventually implement support for the `OPERATE` keyword, being able to skip really should work. I will look into it now.

**Comment by joakim-hove** [comment]
OK: https://github.com/OPM/opm-parser/pull/839 should fix it.

Observe:

1. In the PR the json configuration for the `OPERATE` keyword is added; this implies that we can *parse*, but not actually internalize the `OPERATE` keyword.
2. As I see it the `ParserContext::PARSE_UNKNWON_KEYWORD` should have done the trick - but it was essential to also add the `ParseContext::PARSE_RANDOM_SLASH`. This very clearly illustrates that when we start with sloppy parsing things can quickly get out of hand.

**Comment by magnesj** [comment]
Closing the issue as it does not have priority for now.
