### ISSUE TITLE
anything in parser changed recenlty causes the folllowing problem?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-parser#876]
I did  not see this problem before.  There are some useful keywords are claimed `not supported`. 

```
Error: Keyword 'NSTACK' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/3D_POLYMER.DATA, line 54

Error: Keyword 'OPTIONS' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/3D_POLYMER.DATA, line 60

Error: Keyword 'GRIDUNIT' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/3D_POLYMER.DATA, line 75

Error: Keyword 'NOECHO' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/3D_POLYMER.DATA, line 80

Error: Keyword 'NOECHO' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/3D_POLYMER.DATA, line 119

Error: Keyword 'NOECHO' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/POLY.INC, line 9

Error: Keyword 'PLMIXPAR' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/POLY.INC, line 40

Error: Keyword 'ECHO' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/POLY.INC, line 65

Error: Keyword 'RPTSOL' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/3D_POLYMER.DATA, line 132

Error: Keyword 'NOECHO' is not supported by flow.
In file /home/kaib/OPM-devel/opm/opm-data/polymer_test_suite/3D_plyshlog/case-shear-thinning/3D_POLYMER.DATA, line 143
```

**Comment by jokva** [comment]
https://github.com/OPM/opm-simulators/pull/756

**Comment by joakim-hove** [comment]
Nothing new - it is just printing 'old news'; however we should probably print a bit more selectively.

**Comment by GitPaean** [comment]
```
Error: Keyword 'PLMIXPAR' is not supported by flow.
```

This is one important keyword though. It causes the simulation broken.

**Comment by GitPaean** [comment]
> OPM/opm-simulators#756

Okay. It is not something related to parser, I will check that PR.

**Comment by jokva** [comment]
> This is one important keyword though. It causes the simulation broken. 

Then it was never working.

**Comment by GitPaean** [comment]
> Then it was never working.

I will check about it. NOT sure about that. The simulation has been working for more than one year.

**Comment by jokva** [comment]
If so, then it's despite PLMIXPAR not being supported. As @joakim-hove points out, OPM/opm-simulators#756 doesn't add anything new.

**Comment by joakim-hove** [comment]
The PR in question was PURELY cosmetic, you are looking at a false positive.

**Comment by GitPaean** [comment]
I am not sure where to look at now. I will test a little to find out. Thanks for the information. If you have some other places to suggest, please let me know. It should be something very recently.

**Comment by joakim-hove** [comment]
Please - the only ting you should do is to submit a PR where you remove the PLMIXPAR keyword from the list of not supported keywords.

**Comment by GitPaean** [comment]
Yes. You arre right. I will correct that list. Something else happened after the recent relese changed the iteration behavior, generating some too large residual and causes the simulation restart for the first step, I will take a look at that later.
