### ISSUE TITLE
Possible bug in IOConfigIntegrationTest

### ISSUE THREAD

**Issue by jokva** [OPM/opm-parser#886]
I think I may have stumbled over either very surprising behaviour in Eclipse or a bug in our test suite. I'd appreciate some second opinions and/or eclipse test runs here.

Let's start with the setting of RTPRST here https://github.com/OPM/opm-parser/blob/master/testdata/integration_tests/IOConfig/RPTRST_DECK.DATA#L492 This should be equivalent to BASIC=0. The manual is pretty clear on it for E300 that it means "turn of restart" and it *seems* to be the case, based on other examples and general wording, for E100 as well. However, the test suite claims that this is supposed to be a step to write a restart file. `RTPRST 2 /` is set two timesteps before.

So the question is: How does eclipse behave here? Will the `RPTRST 0 /` simply be ignored and should restart files be written at the timesteps following 16. July 2001, or are our tests wrong?

**Comment by OPMUSER** [comment]
Well, this test deck has no chance of running in Eclipse too much data is
missing - see the attached zip file.

Run under Eclipse 2015.1

Regards

David Baxendale
david.baxendale@gmail.com

**Comment by jokva** [comment]
Github doesn't seem to let you upload files from email, but regardless it seems like the deck is largely (if not completely) Norne. Do you have an opportunity to run Norne with Eclipse and take note on when it outputs restart files?

**Comment by jokva** [comment]
The most interesting dates are July 2001 through December 2001.

**Comment by OPMUSER** [comment]
Let me  download the model and run it.

The log file for the test run is :
```
 Proprietary Notice
 This application contains the confidential and
 proprietary trade secrets of Schlumberger and may
 not be copied or stored in an information retrieval
 system, transferred, used, distributed, translated,
 or retransmitted in any form or by any means, electronic
 or mechanical, in whole or in part, without the
 express written permission of the copyright owner.

 ECLIPSE is a mark of Schlumberger. Copyright (c)
 1981-2015 Schlumberger. All rights reserved.

 1 READING RUNSPEC
 2 READING DIMENS
 3 READING START
 4 READING GRID

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           THERE ARE NO PHASES PRESENT. SPECIFY KEYWORDS
 @           OIL/WATER/GAS IN THE RUNSPEC SECTION

 @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           THE NUMBER OF WELLS HAS BEEN DEFAULTED TO ZERO
 @           USING KEYWORD WELLDIMS IN THE RUNSPEC SECTION
 @           OR NO WELLS WERE FOUND IN THE SCHEDULE SECTION

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           NO PHASES SPECIFIED AS BEING PRESENT IN RESERVOIR
 @           THERE MUST BE AT LEAST ONE ( OF OIL, WATER AND GAS )

 @--MESSAGE  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           CHECKING FOR LICENSES

 @--MESSAGE  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS
 @                43646 KBYTES
     5 READING DX
     6 READING DY
     7 READING DZ
     8 READING TOPS

 @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @                 108192 VALUES NOT DEFINED IN BOX (  1- 46,  1-112,  1-
22)
 @           OF KEYWORD TOPS
     9 READING SPECGRID
    10 READING SOLUTION

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD SOLUTION IN GRID DATA
    11 READING RPTRST

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD RPTRST   IN GRID DATA
    12 READING BASIC=2

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD BASIC=2  IN GRID DATA
    13 READING RPTSOL

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD RPTSOL   IN GRID DATA
    14 READING FIP=3  S

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD FIP=3  S IN GRID DATA
    15 READING SCHEDULE

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD SCHEDULE IN GRID DATA
    16 READING DATES

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD DATES    IN GRID DATA

 @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           SPURIOUS DATA BEFORE DATES    KEYWORD
 @            14 'NOV' 1997 00:00:00.001 /
 @           /
    17 READING DATES

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD DATES    IN GRID DATA

 @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           SPURIOUS DATA BEFORE DATES    KEYWORD
 @            1 'DEC' 1997 /
 @           /
    18 READING DATES

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD DATES    IN GRID DATA

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @
 @           RUN STOPPED BECAUSE NUMBER OF   ERRORS
 @           EXCEEDS MAXIMUM PERMITTED VALUE (    10).
           43 Mbytes of storage required
  No active cells found
           43 Mbytes (image size)

 Error summary
 Comments               0
 Warnings               4
 Problems               0
 Errors                12
 Bugs                   0
 Final cpu     130.29 elapsed     130.29
 Total number of time steps forced to be accepted          0
```
Regards

David Baxendale
david.baxendale@gmail.com

**Comment by OPMUSER** [comment]
The Norne deck will not run under Eclipse 2015.1, phases are missing and
sections are missing you cannot skip sections.
```
 Proprietary Notice
 This application contains the confidential and
 proprietary trade secrets of Schlumberger and may
 not be copied or stored in an information retrieval
 system, transferred, used, distributed, translated,
 or retransmitted in any form or by any means, electronic
 or mechanical, in whole or in part, without the
 express written permission of the copyright owner.

 ECLIPSE is a mark of Schlumberger. Copyright (c)
 1981-2015 Schlumberger. All rights reserved.

 1 READING RUNSPEC
 2 READING DIMENS
 3 READING START
 4 READING GRID

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           THERE ARE NO PHASES PRESENT. SPECIFY KEYWORDS
 @           OIL/WATER/GAS IN THE RUNSPEC SECTION

 @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           THE NUMBER OF WELLS HAS BEEN DEFAULTED TO ZERO
 @           USING KEYWORD WELLDIMS IN THE RUNSPEC SECTION
 @           OR NO WELLS WERE FOUND IN THE SCHEDULE SECTION

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           NO PHASES SPECIFIED AS BEING PRESENT IN RESERVOIR
 @           THERE MUST BE AT LEAST ONE ( OF OIL, WATER AND GAS )

 @--MESSAGE  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           CHECKING FOR LICENSES

 @--MESSAGE  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS
 @                43646 KBYTES
     5 READING DX
     6 READING DY
     7 READING DZ
     8 READING TOPS

 @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @                 108192 VALUES NOT DEFINED IN BOX (  1- 46,  1-112,  1-
22)
 @           OF KEYWORD TOPS
     9 READING SPECGRID
    10 READING SOLUTION

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD SOLUTION IN GRID DATA
    11 READING RPTRST

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD RPTRST   IN GRID DATA
    12 READING BASIC=2

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD BASIC=2  IN GRID DATA
    13 READING RPTSOL

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD RPTSOL   IN GRID DATA
    14 READING FIP=3  S

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD FIP=3  S IN GRID DATA
    15 READING SCHEDULE

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD SCHEDULE IN GRID DATA
    16 READING DATES

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD DATES    IN GRID DATA

 @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           SPURIOUS DATA BEFORE DATES    KEYWORD
 @            14 'NOV' 1997 00:00:00.001 /
 @           /
    17 READING DATES

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD DATES    IN GRID DATA

 @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           SPURIOUS DATA BEFORE DATES    KEYWORD
 @            1 'DEC' 1997 /
 @           /
    18 READING DATES

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @           UNRECOGNISED KEYWORD DATES    IN GRID DATA

 @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
 @
 @           RUN STOPPED BECAUSE NUMBER OF   ERRORS
 @           EXCEEDS MAXIMUM PERMITTED VALUE (    10).
           43 Mbytes of storage required
  No active cells found
           43 Mbytes (image size)

 Error summary
 Comments               0
 Warnings               4
 Problems               0
 Errors                12
 Bugs                   0
 Final cpu     118.38 elapsed     118.38
 Total number of time steps forced to be accepted          0
```
Regards

David Baxendale
david.baxendale@gmail.com

**Comment by OPMUSER** [comment]
Ignore my last email - I picked the wrong file.

Regards

David Baxendale
david.baxendale@gmail.com

On Tue, Jul 26, 2016 at 12:00 PM, David Baxendale <david.baxendale@gmail.com

> wrote:
> 
> The Norne deck will not run under Eclipse 2015.1, phases are missing and
> sections are missing you cannot skip sections.
> ```
>  Proprietary Notice
>  This application contains the confidential and
>  proprietary trade secrets of Schlumberger and may
>  not be copied or stored in an information retrieval
>  system, transferred, used, distributed, translated,
>  or retransmitted in any form or by any means, electronic
>  or mechanical, in whole or in part, without the
>  express written permission of the copyright owner.
> 
>  ECLIPSE is a mark of Schlumberger. Copyright (c)
>  1981-2015 Schlumberger. All rights reserved.
> 
>  1 READING RUNSPEC
>  2 READING DIMENS
>  3 READING START
>  4 READING GRID
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           THERE ARE NO PHASES PRESENT. SPECIFY KEYWORDS
>  @           OIL/WATER/GAS IN THE RUNSPEC SECTION
> 
>  @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           THE NUMBER OF WELLS HAS BEEN DEFAULTED TO ZERO
>  @           USING KEYWORD WELLDIMS IN THE RUNSPEC SECTION
>  @           OR NO WELLS WERE FOUND IN THE SCHEDULE SECTION
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           NO PHASES SPECIFIED AS BEING PRESENT IN RESERVOIR
>  @           THERE MUST BE AT LEAST ONE ( OF OIL, WATER AND GAS )
> 
>  @--MESSAGE  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           CHECKING FOR LICENSES
> 
>  @--MESSAGE  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS
>  @                43646 KBYTES
>      5 READING DX
>      6 READING DY
>      7 READING DZ
>      8 READING TOPS
> 
>  @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @                 108192 VALUES NOT DEFINED IN BOX (  1- 46,  1-112,  1-
> 22)
>  @           OF KEYWORD TOPS
>      9 READING SPECGRID
>     10 READING SOLUTION
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           UNRECOGNISED KEYWORD SOLUTION IN GRID DATA
>     11 READING RPTRST
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           UNRECOGNISED KEYWORD RPTRST   IN GRID DATA
>     12 READING BASIC=2
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           UNRECOGNISED KEYWORD BASIC=2  IN GRID DATA
>     13 READING RPTSOL
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           UNRECOGNISED KEYWORD RPTSOL   IN GRID DATA
>     14 READING FIP=3  S
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           UNRECOGNISED KEYWORD FIP=3  S IN GRID DATA
>     15 READING SCHEDULE
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           UNRECOGNISED KEYWORD SCHEDULE IN GRID DATA
>     16 READING DATES
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           UNRECOGNISED KEYWORD DATES    IN GRID DATA
> 
>  @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           SPURIOUS DATA BEFORE DATES    KEYWORD
>  @            14 'NOV' 1997 00:00:00.001 /
>  @           /
>     17 READING DATES
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           UNRECOGNISED KEYWORD DATES    IN GRID DATA
> 
>  @--WARNING  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           SPURIOUS DATA BEFORE DATES    KEYWORD
>  @            1 'DEC' 1997 /
>  @           /
>     18 READING DATES
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @           UNRECOGNISED KEYWORD DATES    IN GRID DATA
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 6-NOV-1997):
>  @
>  @           RUN STOPPED BECAUSE NUMBER OF   ERRORS
>  @           EXCEEDS MAXIMUM PERMITTED VALUE (    10).
>            43 Mbytes of storage required
>   No active cells found
>            43 Mbytes (image size)
> 
>  Error summary
>  Comments               0
>  Warnings               4
>  Problems               0
>  Errors                12
>  Bugs                   0
>  Final cpu     118.38 elapsed     118.38
>  Total number of time steps forced to be accepted          0
> ```
> Regards
> 
> David Baxendale
> david.baxendale@gmail.com
>

**Comment by OPMUSER** [comment]
Okay, I re-ran the NORNE_ATW2013 model and have uploaded all the results.

The restart files were written as follows:
```
restart file
D:\User\BaxendaleD\Development\OPM\TestRuns\Nornde\NORNE_ATW2013.PRT
 @           RESTART FILE WRITTEN   REPORT     0  
 @           RESTART FILE WRITTEN   REPORT     1  
 @           RESTART FILE WRITTEN   REPORT     2  
 @           RESTART FILE WRITTEN   REPORT     3  
 @           RESTART FILE WRITTEN   REPORT     4  
 @           RESTART FILE WRITTEN   REPORT     5  
 @           RESTART FILE WRITTEN   REPORT    10  
 @           RESTART FILE WRITTEN   REPORT    19  
 @           RESTART FILE WRITTEN   REPORT    27  
 @           RESTART FILE WRITTEN   REPORT    33  
 @           RESTART FILE WRITTEN   REPORT    44  
 @           RESTART FILE WRITTEN   REPORT    53  
 @           RESTART FILE WRITTEN   REPORT    62  
 @           RESTART FILE WRITTEN   REPORT    72  
 @           RESTART FILE WRITTEN   REPORT    77  
 @           RESTART FILE WRITTEN   REPORT    83  
 @           RESTART FILE WRITTEN   REPORT    95  
 @           RESTART FILE WRITTEN   REPORT    98  
 @           RESTART FILE WRITTEN   REPORT   101  
 @           RESTART FILE WRITTEN   REPORT   109  
 @           RESTART FILE WRITTEN   REPORT   112  
 @           RESTART FILE WRITTEN   REPORT   113  
 @           RESTART FILE WRITTEN   REPORT   114  
 @           RESTART FILE WRITTEN   REPORT   115  
 @           RESTART FILE WRITTEN   REPORT   116  
 @           RESTART FILE WRITTEN   REPORT   117  
 @           RESTART FILE WRITTEN   REPORT   118  
 @           RESTART FILE WRITTEN   REPORT   119  
 @           RESTART FILE WRITTEN   REPORT   120  
 @           RESTART FILE WRITTEN   REPORT   124  
 @           RESTART FILE WRITTEN   REPORT   129  
 @           RESTART FILE WRITTEN   REPORT   132  
 @           RESTART FILE WRITTEN   REPORT   141  
 @           RESTART FILE WRITTEN   REPORT   148  
 @           RESTART FILE WRITTEN   REPORT   157  
 @           RESTART FILE WRITTEN   REPORT   161  
 @           RESTART FILE WRITTEN   REPORT   164  
 @           RESTART FILE WRITTEN   REPORT   165  
 @           RESTART FILE WRITTEN   REPORT   166  
 @           RESTART FILE WRITTEN   REPORT   167  
 @           RESTART FILE WRITTEN   REPORT   168  
 @           RESTART FILE WRITTEN   REPORT   169  
 @           RESTART FILE WRITTEN   REPORT   170  
 @           RESTART FILE WRITTEN   REPORT   171  
 @           RESTART FILE WRITTEN   REPORT   172  
 @           RESTART FILE WRITTEN   REPORT   180  
 @           RESTART FILE WRITTEN   REPORT   185  
 @           RESTART FILE WRITTEN   REPORT   188  
 @           RESTART FILE WRITTEN   REPORT   192  
 @           RESTART FILE WRITTEN   REPORT   193  
 @           RESTART FILE WRITTEN   REPORT   194  
 @           RESTART FILE WRITTEN   REPORT   195  
 @           RESTART FILE WRITTEN   REPORT   196  
 @           RESTART FILE WRITTEN   REPORT   199  
 @           RESTART FILE WRITTEN   REPORT   206  
 @           RESTART FILE WRITTEN   REPORT   212  
 @           RESTART FILE WRITTEN   REPORT   221  
 @           RESTART FILE WRITTEN   REPORT   226  
 @           RESTART FILE WRITTEN   REPORT   231  
 @           RESTART FILE WRITTEN   REPORT   235  
 @           RESTART FILE WRITTEN   REPORT   237  
 @           RESTART FILE WRITTEN   REPORT   238  
 @           RESTART FILE WRITTEN   REPORT   239  
 @           RESTART FILE WRITTEN   REPORT   240  
 @           RESTART FILE WRITTEN   REPORT   241                             
```
[NORNE_ATW2013.zip](https://github.com/OPM/opm-parser/files/383027/NORNE_ATW2013.zip)

**Comment by jokva** [comment]
Splendid, thanks, I'll have a look.

**Comment by jokva** [comment]
Ok, I think I've figured this out. Eclipse is beyond insane, but that shouldn't be news to anyone.

See, the thing is it essentially sets `BASIC=0` which turns off restart writing. Except it only turns off restart writing *goverened by `RPTRST`*, not by `RPTSCHED`. There's probably an `RPTSCHED` in there somewhere switched on, which would be overriden by `RPTRST` when it exists, but now that it's turned off it's anyone's game.

Fun.

**Comment by OPMUSER** [comment]
Most of these inconsistencies are caused by adding additional features (with new keywords) over the years and still having to obtain backward compatibility with existing input decks. So it is not as if they don't realize this, it is just how they could satisfy both new and existing features. For example, very few engineers  use this form of the `RPTSCHED`
```
RPTSCHED 
 0 0 0 0 0 0 2 2 2 0 1 1 0 1 1 0 0 / 
```
This goes back to the very first release of Eclipse

OPM on the other other hand can start a fresh ;-)

Ideally, you should mimic Eclipse, but if it is too convoluted , just issue a warning/message saying what you have encountered and the action taken by OPM. The engineers can always modify the deck to get what they want, not a big deal here.

**Comment by alfbr** [comment]
> Ideally, you should mimic Eclipse, but if it is too convoluted , just issue a warning/message saying what you have encountered and the action taken by OPM.

Thanks for you feed-back, greatly appreciated! In the case of RPTSCHED this is basically the approach we have taken. I do not envision that we will ever support everything in RPTSCHED, so this will probably forever be in the category of partially supported keywords with an ongoing effort to provide an informative warning message.

**Comment by jokva** [comment]
It's not too hard to replicate, it's just that Eclipse documentation is ambiguous at best, or maybe just wrong. Regardless, the "correct" behaviour is maintained. Closing.
