### ISSUE TITLE
The size of FIPNUM is not number of cells?

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-parser#888]
I tried to get FIPNUM from parser like this way,
``
std::vector<int> fipnum = eclipse_state_->get3DProperties().getRegions("FIPNUM");
``
But found out that this vetor only contains 17 numbers for NORNE, that is the non-zero number in FIPNUM keywords plus 0, I just wonder how do we know one cell belong to which FIP region through this vector?

**Comment by joakim-hove** [comment]
> I tried to get FIPNUM from parser like this way,
 std::vector<int> fipnum = eclipse_state_->get3DProperties().getRegions("FIPNUM"); 

That will return a vector of the *distinct* values in `FIPNUM` array. I guess what you want is just:
```C++
const std::vector<int>& fipnum = eclipse_state_->get3DProperties().getIntGridProperty("FIPNUM").getData();
```

**Comment by qilicun** [comment]
I will try that, thanks!
