### ISSUE TITLE
Duplicate UnitSystem.cpp?

### ISSUE THREAD

**Issue by babrodtk** [OPM/opm-parser#906]
The following appears on my system:
```
./opm-parser/opm/parser/eclipse/Units/UnitSystem.hpp
./opm-parser/opm/parser/eclipse/Units/UnitSystem.cpp
./opm-parser/opm/parser/eclipse/Parser/UnitSystem.cpp
```
Should the Parser/UnitSystem.cpp file be deleted?

**Comment by jokva** [comment]
Yes. It can safely be just deleted as well, it's not in the CMakeList.txt either.

**Comment by pgdr** [comment]
I'm closing this as the corresponding solution PR has been merged.  Reopen if necessary.
