### ISSUE TITLE
Flow broke on Norne

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-parser#917]
Today I have all my modules updated to the latest version. 
This is issue with flow, but I found the error message is in opm-parse EclipseGrid. 
================ Starting main simulation loop ===============

Time step    0 at day 0/3312, date = 06-Nov-1997

Adaptive time step (0), stepsize 2.64 days.
well iterations = 1, non-linear iterations = 5, total linear iterations = 42
Warning: Keyword 'BASIC' is unhandled for output to file.
Adaptive time step (1), stepsize 5.36 days.
well iterations = 1, non-linear iterations = 9, total linear iterations = 109
Warning: Keyword 'BASIC' is unhandled for output to file.
Warning: Keyword 'BASIC' is unhandled for output to file.
Program threw an exception: Input vector must have full size
[Inferior 1 (process 4811) exited with code 01]

**Comment by blattms** [comment]
This should be fixed by merge of OPM/opm-simulators#825
