### ISSUE TITLE
For a keyword, some items are only used under E300

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-parser#957]
How should we handle them in the definition of the keywords?

I think the current approach is to ignore them. Like `GCONPROD`. 

In the definition, we defined 15 items. In the manual, it has 21 items. Item 16 to item 19 are only valid for E300. 

We have a deck now specifies 16 items. OPM can not parse it now.  

If we want to complete the definition, should we add the definition for item 16 to item 19 or we should only add the definition of item 20 to 21?

I think we can just add all of them without using some of them. Any comment?

**Comment by OPMUSER** [comment]
My comment is to add all (including defaults) and issue warning message 
for the parameters OPM does not use.
ThunderBird Signature File

Regards, David Baxendale Email: David.Baxendale@gmail.com

------------------------------------------------------------------------

**Comment by joakim-hove** [comment]
> I think the current approach is to ignore them. Like GCONPROD.

You are right that when it comes to kewyords / items which behave differently in E100 and E300 the current state is somewhat arbitrary. But we actually have infrastructure to do this Right&trade; - you can add two versions of the keyword - one in the `000_Eclipse100/` directory and one in the `001_Eclipse300/` directory: https://github.com/OPM/opm-parser/tree/master/opm/parser/share/keywords

The parser will load keywords in the numeric order given by the leading three digit number, and the last loaded keyword will take presedence. So if you add a Eclipse300 version in the `001_Eclipse300/`directory that will be the eventual behavior of the parser.

**Comment by GitPaean** [comment]
Solution given. Closing the issue now.
