### ISSUE TITLE
Model 2 does not run with current master

### ISSUE THREAD

**Issue by totto82** [OPM/opm-parser#959]
I get "Error: Program threw an exception: Input argument does not correspond to an active cell" when I try to run Model 2 with flow after updating to current master. I didn't spot any smoking guns among the PRs after the release. Any idea on where to look? The error comes from mapping from global to local index in EclipseGrid.cpp

**Comment by GitPaean** [comment]
Reproduced from my side. I was able to run on Monday. (99% sure)

**Comment by joakim-hove** [comment]
My hunch would be the following [code](https://github.com/OPM/opm-output/blob/master/opm/output/eclipse/Summary.cpp) in opm-output. If that is right - the problem comes from one of `Cxxx` keywords in the `SUMMARY`section. Can you post that section?

**Comment by joakim-hove** [comment]
OK - try this: https://github.com/OPM/opm-output/pull/126

**Comment by totto82** [comment]
I didn't fix the problem. I also get the same problem if I comment out the SUMMARY section. I can debug an try to localize the problem.

**Comment by totto82** [comment]
It runs if I disable output `output_ecl=false` So the problem is in opm-output, but OPM/opm-output#126 did not fix it.

**Comment by joakim-hove** [comment]
>It didn't fix the problem. I also get the same problem if I comment out the SUMMARY section. I can debug an try to localize the problem.

OK; can you post a traceback.

**Comment by totto82** [comment]
I tried to run flow in Debug mode to identify the source of this error, but instead I got a segmentation fault in the initialization. This couldn't related to this problem. I even updated ert as I thought it may be related to the issue reported in OPM/opm-output#124.  @atgeirr Is flow in Debug mode supposed to work?

**Comment by joakim-hove** [comment]
OK - I have merged  OPM/opm-output#126 - as it fixed a real problem anyway.

**Comment by GitPaean** [comment]
A backtrace, hope it will help some. 
```
Breakpoint 1, Opm::EclipseGrid::activeIndex (this=this@entry=0x14bf6878, globalIndex=globalIndex@entry=683706) at /home/kaib/OPM-master-test/debug/opm-parser/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp:234
234	            throw std::invalid_argument("Input argument does not correspond to an active cell");
(gdb) backtrace 
#0  Opm::EclipseGrid::activeIndex (this=this@entry=0x14bf6878, globalIndex=globalIndex@entry=683706) at /home/kaib/OPM-master-test/debug/opm-parser/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp:234
#1  0x00000000008081ed in Opm::out::RegionCache::RegionCache (this=0x14bf6910, state=..., grid=...) at /home/kaib/OPM-master-test/debug/opm-output/opm/output/eclipse/RegionCache.cpp:50
#2  0x00000000007fdba8 in Opm::EclipseWriter::Impl::Impl (this=0x14bf6870, eclipseState=..., grid_=...) at /home/kaib/OPM-master-test/debug/opm-output/opm/output/eclipse/EclipseWriter.cpp:427
#3  0x00000000007fe390 in Opm::EclipseWriter::EclipseWriter (this=0x7fffffffd510, es=..., grid=...) at /home/kaib/OPM-master-test/debug/opm-output/opm/output/eclipse/EclipseWriter.cpp:818
#4  0x0000000000657422 in Opm::FlowMainBase<Opm::FlowMain<UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >, UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >::writeInit (this=0x7fffffffda70)
    at /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/FlowMain.hpp:750
#5  Opm::FlowMainBase<Opm::FlowMain<UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >, UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >::execute (this=this@entry=0x7fffffffda70, argc=argc@entry=2, argv=argv@entry=0x7fffffffdd48)
    at /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/FlowMain.hpp:150
#6  0x0000000000584b9b in main (argc=2, argv=0x7fffffffdd48) at /home/kaib/OPM-master-test/debug/opm-simulators/examples/flow.cpp:41
```

**Comment by joakim-hove** [comment]
> A backtrace, hope it will help some.

OK - thank you; try this: https://github.com/OPM/opm-output/pull/127 - I think that should fix the problem; although I am uncertain if it is the Right&trade; fix.

**Comment by totto82** [comment]
Thanks. It worked.

**Comment by atgeirr** [comment]
> Is flow in Debug mode supposed to work?

A definite yes. If you get a segfault it points to a real problem (perhaps unrelated to what was addressed here), and we should look into it. I ran norne (well, some timesteps at least) in debug mode yesterday, so it should definitely not segfault in the initialization!

**Comment by jokva** [comment]
Fixed it seems, reopen if not.
