### ISSUE TITLE
About SKIPREST

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-parser#960]
Currently, OPM will throw an exception if there is no RESTART, 
```
Error in deck: Can not supply SKIPREST keyword without a preceeding RESTART
```

Looks like E100 will just ignore it without giving warning (I am not totally sure about the warning part, while the model can run through no problem.).

**Comment by GitPaean** [comment]
Sorry. I did not see issue #773. closing this one now.

**Comment by jokva** [comment]
https://github.com/OPM/opm-parser/pull/963
