### ISSUE TITLE
cJSON headers get intermixed.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-parser#964]
I installed a current version of cJSON on my system which is found by opm-parser. The new version changed the identifiers used for the type. Unfortunately, it seems like opm/json/JSonObject.cpp still uses opm/json/cjson/cJSON.h which results in an exception when createDefaultKeywordList is run.

**Comment by blattms** [comment]
The problem is that the include is `/usr/include` and CMake simply ignores that in include_directories as it is a system include directory. In addition the current source directory seems to be always in the include search path.

**Comment by blattms** [comment]
BTW will cook up patches.

**Comment by joakim-hove** [comment]
> [....] Unfortunately, it seems like opm/json/JSonObject.cpp still uses opm/json/cjson/cJSON.h which results in an exception when createDefaultKeywordList is run.

This was a first - I guess it had to come. To be honest the relevant cmake code was written with a silent expectation: "No one is going to have a system installed cJSON" - that has most probably never worked. 

> BTW will cook up patches.

That would be *highly* appreciated :-)
