### ISSUE TITLE
build breaks on ARM

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-parser#971]
on my ARM machine (with Raspbian "Jessie"), I get the following build error for opm-parser:

```
and@bananus:~/src/opm-parser|master > make
[  1%] Built target opmjson
[  2%] Built target runjsonTests
[ 11%] Built target buildParser
[ 12%] Built target createDefaultKeywordList
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```

also, for the first stage of the build (i.e., when compiling the code generator), I get warnings due to the `generated-source` directory not being present yet:

```
and@bananus:~/src/opm-parser|master > make
[...]
Scanning dependencies of target buildParser
[  2%] Building CXX object opm/parser/eclipse/CMakeFiles/buildParser.dir/RawDeck/StarToken.cpp.o
cc1plus: warning: /home/and/src/opm-parser/generated-source/include: No such file or directory
[  2%] Building CXX object opm/parser/eclipse/CMakeFiles/buildParser.dir/RawDeck/RawKeyword.cpp.o
cc1plus: warning: /home/and/src/opm-parser/generated-source/include: No such file or directory
[  3%] Building CXX object opm/parser/eclipse/CMakeFiles/buildParser.dir/RawDeck/RawRecord.cpp.o
cc1plus: warning: /home/and/src/opm-parser/generated-source/include: No such file or directory
[  3%] Building CXX object opm/parser/eclipse/CMakeFiles/buildParser.dir/Parser/ParseContext.cpp.o
cc1plus: warning: /home/and/src/opm-parser/generated-source/include: No such file or directory
[  4%] Building CXX object opm/parser/eclipse/CMakeFiles/buildParser.dir/Parser/MessageContainer.cpp.o
cc1plus: warning: /home/and/src/opm-parser/generated-source/include: No such file or directory
[...]
```

**Comment by atgeirr** [comment]
That sounds like a nice new frontier... Soon all the smartphones in the world will run porous media simulators!

That aside, could it be that the platform simply does not support all locales, in particular the one requested? (And which is requested?)

**Comment by andlaus** [comment]
> That sounds like a nice new frontier... Soon all the smartphones in the world will run porous media simulators!

err, no. ;) the idea is to root out x86 specific issues...

> That aside, could it be that the platform simply does not support all locales, in particular the one requested? (And which is requested?)

maybe. but the code generator is not supposed to be dependent on the locale!?

**Comment by andlaus** [comment]
I forgot:

```
and@bananus:~ > echo $LANG
en_US.UTF-8
```

(this is the default. besides this I installed the `libboost-all-dev` package, so everything and the kitchen sink should be installed, at least boost-wise.)

**Comment by andlaus** [comment]
ok, I've found the reason for this issue: it is the "LC_TIME" environment variable. after unsetting it, the code generator worked. Still, this is not supposed to happen?

(for whatever reason LC_TIME was set to `de_DE.UTF-8` on that machine...)

**Comment by jokva** [comment]
Probably just from boost string operations always being locale aware. I suppose it would be nice to reduce the reliance on boost string handling since we don't care about locales anyway, but it takes time from other things.

**Comment by andlaus** [comment]
yeah, I'd say that fixing this should be "high medium" priority since this occurence was not the first time this caused issues for me in installs where I just used the defaults and I guess I won't be the only one who will run into it...

**Comment by pgdr** [comment]
Let's take a couple of seconds to reflect on the suggestion that fixing building a _three-face reservoir simulator_ on Raspberry Pi should have "high medium" priority.

**Comment by jokva** [comment]
I think the suggestion is not so much about the pi as it is about not working without configuring locales on your off-the-shelf workstation.

**Comment by andlaus** [comment]
> Let's take a couple of seconds to reflect on the suggestion that fixing building a three-face reservoir simulator on Raspberry Pi should have "high medium" priority.

that was not what I meant: I suggested that fixing the locale issues should get that priority. (they will equally appear on any other machine.)

**Comment by andlaus** [comment]
(the issue just happened to be uncovered on that pi.)

**Comment by pgdr** [comment]
Yes yes ... :)

There are many things that should be done to make building OPM smoother *cough*like reducing number of repos to single-digit*cough*

**Comment by andlaus** [comment]
> There are many things that should be done to make building OPM smoother coughlike reducing number of repos to single-digitcough

are you sure that it would make the lives of us developers easier if (for example) code like opm-verteq could break your build if you're really only interested in non-ECL twophase simulations? I thus think "lean and mean" modules are good to keep developers focused while users should primarily stick to the releases via packages. (that's why we release relatively often and provide packages for them.) IMO the current OPM module structure primarily suffers from the fact that some modules are not very focused...

**Comment by atgeirr** [comment]
To the locale issue: it arose also on a plain Ubuntu VM, causing me to add Note 3 on this page:

http://opm-project.org/?page_id=245

If we can become less (an by that I mean un-) sensitive to locale that is a big plus, as it can be a total roadblock to a user.

**Comment by pgdr** [comment]
> are you sure that it would make the lives of us developers easier

Yes!  But let's take this discussion in another forum.  But I sincerely believe that [monolithic repositories increase developer productivity](http://gregoryszorc.com/blog/2014/09/09/on-monolithic-repositories/).

**Comment by andlaus** [comment]
> Yes! But let's take this discussion in another forum.

agreed: we disagree ;)

> But I sincerely believe that monolithic repositories increase developer productivity.

while I partially agree, there's a tradeoff as usual: putting e.g. the linux kernel, firefox and libreoffice into the same repo would certainly not be more productive than what we have currently.

**Comment by pgdr** [comment]
> putting e.g. the linux kernel, firefox and libreoffice into the same repo

Look, I can also be ridiculous:  _Let's put every file in its own repo!_

**Comment by akva2** [comment]
i personally would much prefer that to the monolith alternative. i can do whatever i want with split repos, even in the extreme, it's just a matter of tooling and scripting. with a monolith i need to hack it to bits and pieces to do the equivalent and those hacks i need to maintain for as long as i use the changed code.

**Comment by andlaus** [comment]
> Look, I can also be ridiculous: Let's put every file in its own repo!

yeah, that's a perfect example of the trade off I've mentioned above: too many small unfocused repos are bad because you end up in "dependency hell", but too few are also bad because you probably don't want to be forced to buy and maintain a bike shed in Sibiria when all you want to have is a new car.

On a slightly different note, if I understood it correctly, the biggest point of the article you've linked to above is that monolitic repos allow people to move more easily between projects? IMO being part of an organization on github amounts the same effect, i.e., everyone can -- in principle -- push commits to any repo of the OPM org. On the other side, the article mentions the occasional need for per-directory access control. in practice this IMO amounts to the same effect as having multiple repos.

**Comment by alfbr** [comment]
I can only see one reasonable argument for splitting the reservoir simulator code into multiple repos, and that is enabling easy usage of code outside the simulator.

**Comment by andlaus** [comment]
> that is enabling easy usage of code outside the simulator.

you should generalize that statement a bit: notice that a modular approach makes it much easier to re-use of code in alternative contexts; E.g., it's unlikely that doing the frankenstein branch would have been possible with the old parser (remember that this one was hard-baked into the opm-porsol solver).

Also, is it just my personal impression or do all of these monolithic repo arguments not equally apply to merging all of OPM with the dune project (and going back to pre-Dune 1.0 where everything was monolithic)? If you're for this, raise your hands. ;)

**Comment by alfbr** [comment]
>  it's unlikely that doing the frankenstein branch would have been possible with the old parser

You are arguing that code needs to be split in multiple repos in order to make it modular. Do you really believe that?

> all of these monolithic repo arguments not equally apply to merging all of OPM with the dune project

I fail to see the relevance. Dune is a different project. Moreover, Dune is split into repos making it easy for us to use parts outside Dune. It is exactly the use case I was referring to, and Dune was intended to be used that way from day one AFAIK.

**Comment by andlaus** [comment]
> You are arguing that code needs to be split in multiple repos in order to make it modular. Do you really believe that?

I'm not arguing that way, I'm arguing that modular code does not necessarily require  separate repos but I'm convinced that having separate repos generally increases the discipline of keeping the code modular. also note that I don't think that it matters too much whether you call something a "repo" or a "subdirectory of a repo" because you'll basically have to solve the same issues (as nicely outlined by the article linked to by @pgdr above).

> Dune is a different project

yeah, I'm not arguing for attempting a merger. Rather, where do we draw the line in the sand?

> Dune is split into repos making it easy for us to use parts outside Dune

that's exactly the point: The same thing applies to projects which want to build their stuff on top of OPM. For example, having to deal with a full windows port of simulator code to make the parser usable by ResInsight (whilst ResInsight does not use any simulator code) is probably not the kind of situation we want to be in...

> Dune was intended to be used that way from day one AFAIK.

IMO, OPM should consider itself as a -- more targeted than Dune -- simulation toolbox as well.

**Comment by pgdr** [comment]
@andlaus I didn't want to continue this discussion in the thread, but you raise some questions that are very easy to answer, so let me just answer them, and then continue discussing offline.

> if I understood it correctly, the biggest point of the article you've linked to above is that monolitic repos allow people to

Yes, no, then you clearly did not understand it correctly.

> ...  per-directory access control.

No, this is not about that matter at all.

>  in practice this IMO amounts to the same effect as having multiple repos.

No, because there is a major difference between downloading and (c)making 1 repo with 10 folders and 10 repos with one folder each.  That holds true for development _and_ for the effort our poor build servers are doing.

>  is it just my personal impression or do all of these monolithic repo arguments not equally apply to merging all of OPM with the dune

It's just your personal impression, and I have no idea how you reached that conclusion ...

> Rather, where do we draw the line in the sand?

Well, we could start looking at the opm modules.  They are clearly highlighted on our website [opm-project/modules](http://opm-project.org/?page_id=274).

**Comment by andlaus** [comment]
> No, because there is a major difference between downloading and (c)making 1 repo with 10 folders and 10 repos with one folder each.

I suppose that difference comes down to this:

```
for TMP in opm-{common,parser,output,material,core,grid,simulators} ewoms do
  git clone git@github.com:OPM/$TMP.git
done
```

versus

```
git clone git@github.com:OPM/allofopm.git
```

(the latter would probably take longer and you'll run into issues if not everyone shall have all rights on everything.)

> I have no idea how you reached that conclusion ...

simple: there's a huge functional overlap between the projects.

> Well, we could start looking at the opm modules. They are clearly highlighted on our website opm-project/modules.

yeah, I think we agree that the current module structure is far from optimal and that it should be improved. (as I see it, we just don't agree on whether the end result should be a single monolithic repo or not.)

**Comment by jokva** [comment]
Module discussion aside, I don't think it's unreasonable to tune the AOT parser keyword compilation to not crash on poorly configured locales. Care to make an issue?

**Comment by andlaus** [comment]
> I don't think it's unreasonable to tune the AOT parser keyword compilation to not crash on poorly configured locales. Care to make an issue?

yeah, in particular since this seems to be quite common (in the sense that installing a recent Ubuntu with a non-English locale will probably trigger it). I'll open a separate issue and close this one.

**Comment by alfbr** [comment]
> yeah, I think we agree that the current module structure is far from optimal and that it should be improved.

That is one of the fundamental problems. It is never optimal, continuously reorganising repos is a major resource hog.

**Comment by andlaus** [comment]
> That is one of the fundamental problems. It is never optimal, continuously reorganising repos is a major resource hog.

yeah, I guess that's a fact of life of any non-trivial organization. not doing anything will be a larger issue in the long run, though. (it will lead to stifling everything.)
