### ISSUE TITLE
Allow for changes in HEAD_I location in WELSPECS during simulation

### ISSUE THREAD

**Issue by totto82** [OPM/opm-parser#984]
The HEAD_I location in WELSPECS is supposed to be able to change during the run. It happens in some Model 2 realizations.  But now the parser throws "Program threw an exception: Unable process WELSPECS for well XXX, HEAD_I deviates from existing value" If the well head i,j coordinates changes.

**Comment by joakim-hove** [comment]
> The HEAD_I location in WELSPECS is supposed to be able to change during the run. It happens in some Model 2 realizations. But now the parser throws "Program threw an exception: Unable process WELSPECS for well XXX, HEAD_I deviates from existing value" If the well head i,j coordinates changes.

OK - this was surprising; I'll try to call you to get a bit more context.
